### ISSUE TITLE
cfs--set-font: Invalid font name

### ISSUE THREAD

**Issue by deftsp** [tumashu/chinese-fonts-setup#11]
`C-c C-c` 报错:
```
cfs--set-font: Invalid font name: -*-SimSun-ExtB-normal-normal-normal-*-*-115-*-*-m-0-iso10646-1
```
e11759b809f35b7f2df7961e315f05a159f6c33a 这个版本没这个问题。

on OS X: 10.10.2。 系统是有这个字体的。

**Comment by tumashu** [comment]
这个问题是emacs XLFD 解析器的bug，见 bug#17457: 
  
     http://lists.gnu.org/archive/html/bug-gnu-emacs/2014-05/msg00422.html

简单来说，就是字体名称中包含“-”，结果导致生成的XLFD，不是一个有效的XLFD，

XLFD 的相关知识可以参考：

  http://www.gnu.org/software/emacs/manual/html_node/emacs/Fonts.html#Fonts

当前可以做的就是，忽略名称中包含“-”的字体。
