### ISSUE TITLE
OSX下没有作用

### ISSUE THREAD

**Issue by passchaos** [tumashu/chinese-fonts-setup#13]
如题在OSX下使用没有作用。奇怪的是通过elpa安装不能自动加载，需要手动加载对应的el文件。

**Comment by tumashu** [comment]
你这个 “没有作用” 是什么意思？ 不能调整对齐？ 还是什么的？

通过elpa安装的，确实需要在.emacs 中加入：

```
(require 'chinese-fonts-setup)
```

**Comment by passchaos** [comment]
是字号的原因，我将fallback中字号中文调为英文的1.2倍就好了。是不是可以设置字号的放缩，使用font-rescale？

**Comment by tumashu** [comment]
你看看chinese-pyim的README吧，字体对齐功能不是你这么设置的。。。。

**Comment by passchaos** [comment]
EXT-B字体为何怎么设置字号都不能对齐？

**Comment by tumashu** [comment]
EXT-B 字体名称中如果有 “-” ,这个字体是无法起作用的，所以说，无法对齐字体，最可能的原因是：你设置的 EXT-B 字体名称中有“-”, chinese-fonts-setup 无法识别，系统恰好找了你设置的字体fallback。

**Comment by tumashu** [comment]
安装一个字体名称中无“-”的EXT-B字体吧
