### ISSUE TITLE
可否使用增大字体间距的方式对齐？

### ISSUE THREAD

**Issue by passchaos** [tumashu/chinese-fonts-setup#14]
我对emacs lisp不熟，源文件中的方法应该还是通过调大中文字体字号，能否像在终端下那样增大中文字体的间距解决对齐呢，因为增大中文字体字号造成中文字符明显偏大很不协调。
另一种方式是使用中文字符字宽严格为英文字符两倍的字体，可在我的博文中看到效果：http://passchaos.com/2015/03/27/org-mode表格内中文对齐.html

**Comment by tumashu** [comment]
增大字体间距这种方式需要直接调整emacs 的c代码，以前有一个 “中英文等宽补丁” 就是使用这种方式，不过那个补丁过期了，不知道有没有人更新。


如果字体明显偏大， 可以使用一个相对偏小的中文字体，比如 “simhei” “楷书” 等，微软雅黑相对来说就偏大。

严格中英文等宽的字体，不需要安装chinese-fonts-setup， 但这种字体相对较少，选择面不宽。
