### ISSUE TITLE
Is it possible to use bold Chinese fonts?

### ISSUE THREAD

**Issue by wpchou** [tumashu/chinese-fonts-setup#15]

**Comment by tumashu** [comment]
possible, but you should hack this function:
``
(defun cfs--make-font-string (fontname fontsize &optional type)
(if (and (stringp fontsize)
(equal ":" (string (elt fontsize 0))))
(format "%s%s" fontname fontsize)
(if fontsize
(cond
((eq type 'bold) (format "%s-%s:weight=bold:slant=normal" fontname fontsize))
((eq type 'italic) (format "%s-%s:weight=normal:slant=italic" fontname fontsize))
((eq type 'bold-italic) (format "%s-%s:weight=bold:slant=italic" fontname fontsize))
(t (format "%s-%s:weight=normal:slant=normal" fontname fontsize)))
(cond
((eq type 'bold) (format "%s:weight=bold:slant=normal" fontname))
((eq type 'italic) (format "%s:weight=normal:slant=italic" fontname))
((eq type 'bold-italic) (format "%s:weight=bold:slant=italic" fontname))
(t (format "%s:weight=normal:slant=normal" fontname))))))
```

**Comment by wpchou** [comment]
I tried, but it seems that it's not so easy.

Usually, to "bold" a character, emacs modes like org mode just use a "FACE". What you have done is using set-face-font to "bind" one font to the "FACE". If set-face-font is the only solution, there are only two options:

- Let's define one specific bold face for Chinese and call it "bold Chinese". When we need to bold a Chinese character, we use that face instead of the original one. But usually we are not the authors. So that's out of our control.

- Maybe we can combine the English and the Chinese font we preferred into a fake font. However, even it's possible, that's not easy.

Anyway, you have done a good job. Thank you! Emacs sucks at dealing Chinese( also Unicodes, I assumed), it searches fonts on my mac alphatically and just uses the first one. You've made it much more comfortable.

**Comment by wpchou** [comment]
Maybe font fallback system like browsers' is the only perfect solution. I assume that's one of the reasons for atom taking advantage of chromium.
