### ISSUE TITLE
Unicode處理問題

### ISSUE THREAD

**Issue by maniux** [tumashu/chinese-fonts-setup#16]
我用的Cygwin。
如果用unicode-font那個包或者什麼都不用，能顯示很多unicode的符號。
用了這個包，中文字體好看很多，但unicode的符號就無法顯示。

弄了很久也沒調整好，不知道什麼情況。
是需要應用的英文字體也包含Unicode符號么？

**Comment by tumashu** [comment]
符号分布很广，有的在英文字体中，有的在中文字体中，有的在ext-b字体中， 最容易的方法还是找一款包含符号比较全的英文字

**Comment by tumashu** [comment]
另外，最好给我发一个测试文件。。。

**Comment by maniux** [comment]
我用的Monaco。

Emacs是cygwin下的，現在還不知道怎麼裝字體。font-cache裝上的好像不算核心字體，emacs識別不了。

下面這些是一部分顯示不了的符號。
其實我要求不高，就是org-bullets的符號顯示不了這個比較難受。

✝✚✡☥⎈☭☪☮☺☹ ☯☰☱☲☳☴☵☶☷
⇐⇒⇑⇓⇔⇗⇦⇨⇧
 ðɫŋɹɾƩθtʒæɑəəɚɜɛɝɪɪ̈ɒɔʊʊ̈ʌ

**Comment by maniux** [comment]
我不確定猜測的對不對，但是感覺好像unicode被限定在中文字體裡了。

我換英文字體，是否能顯示的unicode沒有變化。但如果換中文字體，有些能顯示的unicode符號大小和形狀都會變化。

**Comment by tumashu** [comment]
You can try dajevu font, which include many symbol.

In my debian system, It can show all symbol you note by three fonts: Unifont, 文泉驿等宽微米黑 and PragmataPro

**Comment by tumashu** [comment]
chinese-fonts-setup并没有特别处理symbol，因为symbol包含在各个地方，没法统一处理，但如果使用字体fallback机制显示符号，这就是chinese-fonts-setup的bug了，对symbol的要求我很低，仅仅要求显示，

**Comment by maniux** [comment]
我的意思是，這些符號很多Monaco也能顯示。但用了這個包以後，好像把符號的字體默認為中文了。
就是本來英文字體能顯示，但加了中文以後，讓系統從中文裡面找對應符號，就出錯。

我換英文字體沒反應，但換中文字體就會變化。

**Comment by tumashu** [comment]
嗯，确实有这个问题，但是以我现在的能力，没法从代码的层次解决，因为emacs字体机制太难搞了，我想到的一个解决方案是选择一款包含符号少的中文字体。。。。 只能说抱歉了。。。。

**Comment by maniux** [comment]
不用抱歉啊，包很好用，就是在我這裡狀況比較奇葩。

所以說如果中文字體里沒有的符號，emacs會從英文字體裡面選么？
可在我這裡就顯示亂碼是什麼情況……

**Comment by tumashu** [comment]
```
所以說如果中文字體里沒有的符號，emacs會從英文字體裡面選么？
可在我這裡就顯示亂碼是什麼情況……
```
按理说应该是这样，但实际就不知道了，因为字体设置那一段核心代码，是我让一个emacs盆友写的，我也弄的不是很明白。。。。

**Comment by maniux** [comment]
好吧，多謝耐心回復~

**Comment by maniux** [comment]
實際情況是，對於unicode的符號，系統只從中文裡面找……也就說中文符號越少，顯示就越不全……

不能把unicode map到英文字體上麼？
有個unicode-fonts的package，能非常好的處理這個問題，但是中文顯示難看而且不等寬啊……

**Comment by tumashu** [comment]
Unicode-fonts好复杂呀。。。我研究研究

**Comment by tumashu** [comment]
实在不行，你可以暂时把，chinese fonts setup 中设置symbol 字体的两行代码去掉试试，有中文注释，同学自己找找

**Comment by tumashu** [comment]
记得删除编译文件

**Comment by maniux** [comment]
嗯，我也在看chinese-font-setup的代碼……找到辦法再交流~

**Comment by maniux** [comment]
再。

**Comment by tumashu** [comment]
在有一个以internal结尾的函数中

**Comment by maniux** [comment]
前兩天忙，剛看這個問題。
哪裡有internal結尾的函數……

On 18 July 2015 at 00:18, tumashu <notifications@github.com> wrote:

> 在有一个以internal结尾的函数中
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tumashu/chinese-fonts-setup/issues/16#issuecomment-122433511>
> .
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by maniux** [comment]
http://chriszheng.science/2015/06/03/Chinese-dose-not-have-true-quotation-mark/

On 22 July 2015 at 09:15, X <xliotx@gmail.com> wrote:

> 前兩天忙，剛看這個問題。
> 哪裡有internal結尾的函數……
>
> On 18 July 2015 at 00:18, tumashu <notifications@github.com> wrote:
>
>> 在有一个以internal结尾的函数中
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tumashu/chinese-fonts-setup/issues/16#issuecomment-122433511>
>> .
>>
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by maniux** [comment]
我大概解決了。
主要問題就是沒有什麼字體可以覆蓋全部的symbol。
所以要設定多個symbol，遇到沒有的自動換到下一個。

也就是說profile裡面不只有3個list了，後面加了3-4個list，每個附帶一種symbol字體。
然後set-font-1函數裡面相應的多加上讀取symbol字體的函數。

**Comment by maniux** [comment]
另外就是Chinese Symbol那個要append，不能prepend……不然很多英文symbol會使用中文字體，不好看。

**Comment by tumashu** [comment]
我暂时换不准备在chinese-fonts-setup中完全支持符号字体的配置，就像同学说的，符号太过分散，想要完全支持符号等宽对齐，似乎需要特别复杂的配置。。。

或许我应该只在Chinese-fonts-setup中添加英文符号的配置

**Comment by maniux** [comment]
英文符號：如果不像unicode-font那種map好多font，只要多添加幾個english
symbol的設置就行，一個找不到換下一個。我目前改你的chinese-font-setup.el文件，用了三個，基本上符號就能滿足了，不夠就再加。

中文符號：這個我覺得完全可以取消……因為符號其實都是在符號字體里，目前還沒聽說單獨的中文符號字體。或者把中文符號的匹配放在英文符號後面也行。不然出現符號就會先從中文字體裡面找……

2015-07-30 12:16 GMT+02:00 tumashu <notifications@github.com>:

>
> 我暂时换不准备在chinese-fonts-setup中完全支持符号字体的配置，就像同学说的，符号太过分散，想要完全支持符号等宽对齐，似乎需要特别复杂的配置。。。
>
> 或许我应该只在Chinese-fonts-setup中添加英文符号的配置
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tumashu/chinese-fonts-setup/issues/16#issuecomment-126261486>
> .
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by tumashu** [comment]
恩，我应该给chinese-pyim添加一个后处理hook，这样大家就可以不用修改源代码来实现上述功能了。。。

**Comment by tumashu** [comment]
A hook added,  you can do like this:
```
(defun cfs-set-symbol-fonts (fontsizes-list)
  (set-fontset-font t 'symbol "Inconsolata" nil 'append)
  (set-fontset-font t 'symbol "Symbola" nil 'append)
  (set-fontset-font t 'unicode "Segoe UI Emoji" nil 'append)
  (set-fontset-font t 'unicode "STIX" nil 'append))
(add-hook 'cfs-set-font-finish-hook 'cfs-set-symbol-fonts)
```
