### ISSUE TITLE
OSX下C-c C-c预览的时候非常慢

### ISSUE THREAD

**Issue by isolet** [tumashu/chinese-fonts-setup#17]
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-11 on builder10-9.porkrind.org

请问可能是什么原因？每次按C-c C-c预览都要等几秒出预览窗口，和视频那里秒生效差太远…调起来十分吃力。

**Comment by tumashu** [comment]
没有苹果，所以我没法测试，同学可以试着将下面的变量设置为t看看


cfs-use-face-font-rescale

**Comment by jinn8522** [comment]
我测试了，即使将cfs-use-face-font-rescale这个变量设为t，C-c C-c的时候刷新也是非常慢，即使用emacs -q启动后只手动加载这个chinese-fonts-setup这个包，然后把中英文字体都设为只有一个还是没有办法。另外ext-b 字体也没办法正常加载。我不知道win上这个是不是有用的

**Comment by tumashu** [comment]
welcome patch

**Comment by wd** [comment]
先感谢下作者提供的这个包，实在太赞了。
然后，我也用 osx，没有装 ext-b 字体的情况下，没有出现慢的情况。不过是预览的时候，表格最下面一行字体的大小调整的时候总是不变化的，提示也是 ext-b 字体缺失。
然后安装了那个字体之后，就没有任何问题了。

GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, Carbon Version 157 AppKit 1404.34) of 2015-12-23 on wddeMacBook-Pro.local

**Comment by tumashu** [comment]
好用就好。。。。
