### ISSUE TITLE
Wrong limitation of font size step in cfs--step-fontsize

### ISSUE THREAD

**Issue by aligua** [tumashu/chinese-fonts-setup#18]
(defun cfs--step-fontsize (num) 
   (let* ((profile-name cfs--current-profile-name) 
          (current-step 
           (max 1 (min (+ num (cfs--read-fontsize-step profile-name)) 
                       (length cfs--fontsizes-fallback)))) 这个貌似改成cfs--custom-set-fontsizes 吗？  否则 step 被限制到最大9了 
          (fontsizes-list (cfs--get-fontsizes current-step))) 
     (cfs--set-font fontsizes-list) 
     (cfs--save-fontsize-step profile-name current-step) 
     (message cfs--minibuffer-echo-string)))

**Comment by tumashu** [comment]
cfs--custom-set-fontsizes  只用在配置文件中，不能用在其他地方。。。

对的，chinese-fonts-setup默认只有9个step，太大或者太小的字体都没有什么用处。。。。
```
9   
10  
11.5
12.5
14  
16  
18  
20  
22  
```

**Comment by aligua** [comment]
我觉得大的挺有用的， 有时候我就是想要大大的， 比如有的时候给年纪大的人看，一个字有1.5 厘米 以上还是满正常的。 而且我觉得这个改大了没有什么坏处， 给用户自己选择的机会吧。

**Comment by tumashu** [comment]
添加额外的step可能需要升级profile格式，是个大工程。。。。 你如果想用大字体，可以把cfs--custom-set-fontsizes 中自己22改成更大的字号

**Comment by tumashu** [comment]
我现在将最大的字号设置为： 32， 估计可以满足大多数人的需要了， 不过需要使用 cfs-regenerate-profile 强制覆盖已有的 profile

**Comment by aligua** [comment]
coll enhancement!
