### ISSUE TITLE
请问windows上的字体名称怎么看

### ISSUE THREAD

**Issue by cmal** [tumashu/chinese-fonts-setup#20]
请问windows上的字体名称怎么看？
我在网上下载了一个中文字体文件，可是尝试了很多次，也没办法确定到底应该用哪个名字？试过文件名，打开字体文件之后的字体名和标题名。好像跟这个项目关系不大，但是实在是因为这个项目解决我使用org时的中文问题，折腾字体时遇到的问题，十分感谢！

**Comment by cmal** [comment]
自己回答吧，应该用文件内的字体名。
不好用是因为总共有3个profile，C-c C-c应用测试的时候一定要应用当前的profile才有效果。

**Comment by tumashu** [comment]
1. 把字体扔到 window 字体目录中
2. 运行下面的 elisp 命令：cfs-insert-fontname
