### ISSUE TITLE
Debugger entered--lisp error: (wrong-type-argument integerp nil)

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-fonts-setup#25]
设置了cfs-profiles，使用三种自己设定的模式名字替换掉原本的profile1-3，然后第一次启动emacs
时，提示如下：
```lisp
Debugger entered--lisp error: (wrong-type-argument integerp nil)
cfs--read-fontsize-step("profile1")
cfs-set-font-with-saved-step()
run-hooks(window-setup-step)
（接下来是一堆乱码）
normal-top-level
```

**Comment by saccohuo** [comment]
* 解决方法
启动emacs之后，手动使用`M-x cfs-switch-profile`，切换到三种模式的某一种，再次启动不会再出现该问题。
* 可能原因
可能是初始配置加载时虽然使用了默认的profile配置方式，但是emacs认为你没有手动设置打开emacs时的默认模式，因此默认给了`profile1`的配置，然后调用函数加载`profile1`的配置文件，最后没有发现这个问题，然后提示了这个错误。

**Comment by tumashu** [comment]
thanks

**Comment by saccohuo** [comment]
话说我每次更新cfs，都会再次出现这个问题，需要重新switch-profile，这个算是个小bug吧，可以修复一下吗

**Comment by tumashu** [comment]
Try again

**Comment by saccohuo** [comment]
我从melpa还是不能安装cfs，就是我在微信上跟你描述的情况

**Comment by saccohuo** [comment]
我安装其他package没有问题
