### ISSUE TITLE
能否做到等宽且等高？

### ISSUE THREAD

**Issue by Yevgnen** [tumashu/chinese-fonts-setup#26]
如题...

**Comment by tumashu** [comment]
可以，不过严重依赖字体，大多数时候不可以。。。。

**Comment by Yevgnen** [comment]
依赖字体我觉得事小，毕竟不可以不常换。英文偏好Inconsolata，有推荐中文字体否？即使怎么调缩放，都好像始终无法做到完全等宽等高，只是“看起来”等高，细看还是有差别。只有完全等高才有意义。哪怕好小的差别，在auto-complete的菜单一出来，背后的行就一跳一跳的时大时小。在LaTeX下和org-mode下都用得非常不爽。

<img width="341" alt="screen shot 2016-01-20 at 11 15 53" src="https://cloud.githubusercontent.com/assets/16749790/12439025/35492148-bf67-11e5-8765-fab7e12d790c.png">

**Comment by tumashu** [comment]
只能一个一个试验了，可以试试 simhei

**Comment by Yevgnen** [comment]
好的我试试。顺便问，对Greek Alphabet这类，有字体推荐么？还是和中文刷一样的好？

**Comment by tumashu** [comment]
Greek Alphabe 完全外行，没试过
