### ISSUE TITLE
linux下对苹果的冬青字体调整无效

### ISSUE THREAD

**Issue by mathwu** [tumashu/chinese-fonts-setup#27]
在profile中无论如何设置冬青字体的大小都无法让中英文对齐. 雅黑和其他一些字体可以.

**Comment by tumashu** [comment]
一个可能的问题是，你字体名字设置不对。。。。

**Comment by tumashu** [comment]
今天我稍微更新了一下，你看看能不能识别出你需要的字体

**Comment by tumashu** [comment]
我今天在window下安装了你说的东青字体，识别不了，我估计是字体的原因，没法整，所以我关闭这个issue了。
