### ISSUE TITLE
系统已经安装的字体在emacs下不可以

### ISSUE THREAD

**Issue by Carter-Pro** [tumashu/chinese-fonts-setup#28]
你好，我最近在用emacs写论文，想使用仿宋_GB2312。
我在系统上已经安装了，使用命令(cl-prettyprint (font-family-list))也可以看到。
为什么在使用您的工具设置的时候无法使用这个字体？

**Comment by tumashu** [comment]
运行 cfs-edit-profile 命令，用 cfs-insert-fontname 添加一个名称

**Comment by Carter-Pro** [comment]
我明白您的意思，您是说在字体列表中没有我需要的字体是吧？
我已经添加进去了，还是不能使用。
更准确的说，我尝试了很多中文字体都无法。
我使用的系统是Mac OS X， emacs 25.0.92。

**Comment by tumashu** [comment]
放到字体列表第一位了吗？

**Comment by Carter-Pro** [comment]
@tumashu 知道原因了，我更改完字体没有保存就尝试预览....
麻烦您了！感谢您的代码！
我会关闭该问题

**Comment by Carter-Pro** [comment]
@tumashu 麻烦再问下，如何保存配置？为什么重启之后之前调整的字体大小消失了？

**Comment by tumashu** [comment]
自动保存，你这种情况可能是你在其他地方有字体设置，覆盖了chinese-font-setup的配置。。。

**Comment by liuxueyang** [comment]
@tumashu 

```
运行 cfs-edit-profile 命令，用 cfs-insert-fontname 添加一个名称
```

在minibuffer会提示`Buffer is read-only`，并不能插入新的字体

**Comment by tumashu** [comment]
用 cfs-edit-profile-without-ui 或者你自己设置 cfs-personal-fontnames，fonts-family-list获得的字体名称没法区分英文或者中文，另外一个原因是乱码
