### ISSUE TITLE
﻿Debugger entered--Lisp error: (error "Local variables entry is missing the suffix")

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-fonts-setup#29]
我从 melpa 不能安装 cfs，提示错误 `﻿Debugger entered--Lisp error: (error "Local variables entry is missing the suffix")` 。
似乎是melpa上推送出了问题或者推送的版本有点问题，希望可以修改一下。melpa中其他package的安装没有类似问题。
```
﻿Debugger entered--Lisp error: (error "Local variables entry is missing the suffix")
  signal(error ("Local variables entry is missing the suffix"))
  error("Local variables entry is missing the suffix")
  hack-local-variables()
  autoload-find-file("chinese-fonts-setup.el")
  #[0 "\306\211\211\307\306\310\300!\306\311\300!\306:r\206 
```
下面是问题截图。
![image](https://cloud.githubusercontent.com/assets/13887263/14675562/2d241b68-073c-11e6-9aab-18f1ee0c6535.png)

![image](https://cloud.githubusercontent.com/assets/13887263/14675680/c304e6d0-073c-11e6-9d67-cca1546ae2b9.png)

**Comment by tumashu** [comment]
我这里无法重现这个问题，你是不是用了啥特殊的设置引起冲突了？ 或者删除 elpa中的chinese-fonts-setup，再安装试试

**Comment by saccohuo** [comment]
我看了下，是 generate autoload 的时候产生的这个问题哎

**Comment by tumashu** [comment]
CRLF 的可能性不大，我感觉

**Comment by saccohuo** [comment]
我在windows下把从melpa下载的cfs的.el文件里面的 `^M` 去掉，然后把buffer编码方式设置成了 `utf-8` ，然后可以正常生成autoload文件了

**Comment by tumashu** [comment]
chinese-fonts-setup 本来就是 utf-8-unix 格式的文件呀？
```
;; Local Variables:
;; coding: utf-8-unix
;; End:

;;; chinese-fonts-setup.el ends here
```

**Comment by saccohuo** [comment]
恩，我的意思是 utf-8-unix 改为 utf-8。虽然没有找到这两个具体的区别。。

**Comment by tumashu** [comment]
没这种问题，我所有的包都用 utf-8-unix ，不可能就只有这一个出问题。。。。

**Comment by saccohuo** [comment]
sorry，我测试了一下，使用utf-8-unix也没有问题，重点应该在于把里面的 `^M` 替换掉。
