### ISSUE TITLE
关于TAB对齐的问题

### ISSUE THREAD

**Issue by ernest-dzf** [tumashu/chinese-fonts-setup#30]
先谢谢你的工作，找了一圈还就是这个好用！
一个疑问是，TAB键的对齐功能似乎失效了，在表格的某个域按TAB键的话，会将已经对齐好的表格打乱，然后必须得通过C-c C-c重新对齐，有点不方便。

**Comment by tumashu** [comment]
你说的是org的问题吗？

在 2016-05-03 20:51:14，ernest <notifications@github.com> 写道：


先谢谢你的工作，找了一圈还就是这个好用！
一个疑问是，TAB键的补全功能似乎失效了，在表格的某个域按TAB键的话，会将已经对齐好的表格打乱，然后必须得通过C-c C-c重新对齐，有点不方便。

**Comment by ernest-dzf** [comment]
恩，是的

**Comment by tumashu** [comment]
是不是和补全工具冲突呀？ 关闭 auto-complete 试试

在 2016-05-03 22:08:52，ernest <notifications@github.com> 写道：


恩，是的

**Comment by ernest-dzf** [comment]
> 一个疑问是，TAB键的补全功能似乎失效了

说错了，不是补全功能，是对齐功能失效

**Comment by tumashu** [comment]
这个我也不知道了

在 2016-05-03 22:16:26，ernest <notifications@github.com> 写道：


一个疑问是，TAB键的补全功能似乎失效了

说错了，不是补全功能，是对齐功能失效

**Comment by ernest-dzf** [comment]
你那里可以重现问题吗？

**Comment by tumashu** [comment]
我这里似乎没你说的这个问题






在 2016-05-03 23:05:51，"ernest" <notifications@github.com> 写道：


你那里可以重现问题吗？

**Comment by ernest-dzf** [comment]
我试了一下，这个问题好像是emacs自身的问题。如果我以emacs -Q启动，不加载任何插件。在org文件的表格中的某个域中按C-c C-c和TABLE，对于中英文混排和纯英文，产生的动作是不同的。

如果表格是纯英文，那么通过TABLE或者SHIFT-TABLE在表格中的各个域移动的时候，会附带有realign table的效果（可以对齐），当然C-c C-c也可以对table进行对齐；

如果表格是中英文混排，在通过TABLE或者SHIFT-TABLE在表格中的各个域移动时候，会不断改变表格的布局，最后收敛到一个紧凑的布局，就不再变化（当然还是对不齐），这时候按C-c C-c就会重新调整table的布局（当然也对不齐）

**Comment by tumashu** [comment]
我这里混排都可以对齐，你的字体没有设置为，中英文等宽吧？

**Comment by tumashu** [comment]
我这里混排都可以对齐，你的字体没有设置为，中英文等宽吧？

**Comment by ernest-dzf** [comment]
我也是可以对齐的，C-c C-c就可以将表格对齐。但是通过TAB键在表格中的各个域移动的话，就会打乱布局，然后必须得通过C-c C-c重新将表格对齐。
