### ISSUE TITLE
设置默认字体

### ISSUE THREAD

**Issue by ernest-dzf** [tumashu/chinese-fonts-setup#31]
就我理解而言，chinese-fonts-setup通过预先设置好多个字体组合来达到对齐目的。那我如何设置默认的字体组合呢？

**Comment by tumashu** [comment]
cfs-edit-profile

在 2016-05-22 10:02:41，ernest <notifications@github.com> 写道：


就我理解而言，chinese-fonts-setup通过预先设置好多个字体组合来达到对齐目的。那我如何设置默认的字体组合呢？

**Comment by ernest-dzf** [comment]
![font](https://cloud.githubusercontent.com/assets/16398130/15451845/d5c5d212-2009-11e6-9de3-7f7798693d47.png)
通过cfs-edit-profile可以调整字体。
比如上图，如果我想以（8.5 11.0 11.0）这个组合作为默认字体，该如何做呢？

**Comment by tumashu** [comment]
看看readme吧，有两个命令可以增大或者缩小字体，用他们调整字体大小后，就会自动保存设置

**Comment by ernest-dzf** [comment]
没有起效果。我看了下，调整字体后，确实将相关信息保存在～/.emacs.d/custom.el中，但是下次重新启动的时候，没有效果。

**Comment by ernest-dzf** [comment]
恩，解决了，是我自己自己以前将加载custom.el的代码注释了。谢谢你。
