### ISSUE TITLE
w32下无法全屏

### ISSUE THREAD

**Issue by HomelandScenery** [tumashu/chinese-fonts-setup#32]
大大你好。我很感谢您的插件，让中文在emacs中显示变得几乎完美。但小弟有个疑问，我用了您的插件后，字体大小调到英文16号，但是启动的时间不能全屏。我使用全屏的命令是
`(setq initial-frame-alist (quote ((fullscreen . maximized))))
`
启动后的效果是这样的
![screenshot - 2016_5_28 17_26_25](https://cloud.githubusercontent.com/assets/19407813/15626531/61b84432-24f9-11e6-8d1b-47bddca7c067.png)
请您一定要帮帮我啊，感谢万分。

**Comment by tumashu** [comment]
试试下面的设置，看行不行
```
(setq cfs-keep-frame-size nil)
```

**Comment by HomelandScenery** [comment]
非常感谢作者，已经圆满解决了。多谢。
另有一个疑问，配置文件是否一次最多调用三个？
我在init.el里加了一段`(setq cfs-profiles
    '("program" "org-mode" "read-book" "kaiti"))`
但是当切换到kaiti配置时报错。
`cfs-set-font-with-saved-step: Wrong type argument: number-or-marker-p, nil`
而这个‘kaiti’配置是从另外一个正常显示的配置复制出来，经过'cfs-edit-profile'编辑过的。
请问问题出在哪里？再次麻烦作者。谢谢了

**Comment by tumashu** [comment]
不是， profile没有数量限制，我估计你设置有问题。。。

**Comment by tumashu** [comment]
```
(setq cfs-profiles '("program" "org-mode" "read-book" "kaiti"))
(require 'chinese-fonts-setup)
```
然后使用 cfs-next-profile 切换到 kaiti 这个profile，再用 cfs-edit-profile 编辑，不需要你手动复制

**Comment by HomelandScenery** [comment]
`(setq cfs-profiles`
`       '("program" "org-mode" "kaiti" "read-book"	))' `

我已经复制了配置，切换前面三个profile没有问题，都能正常切换，但是到了第四个“read-book”时，会报错，代码是

`Wrote c:/emacs/.emacs.d/lisp/custom.el [2 times]`
`如果中英文不能对齐，请运行‘cfs-edit-profile’编辑当前profile。`
`cfs-set-font-with-saved-step: Wrong type argument: number-or-marker-p, nil`

即便切换了“read-book”后，也会报错

`Loading c:/emacs/.emacs.d/chinese-fonts-setup/v3/read-book.el (source)...donecfs-set-font-with-saved-step: Wrong type argument: number-or-marker-p, nil`

但是当删除另外三个中任意一个profile，再把该profile在命令中注释掉，“readbook”profile又能正确显示了。所以我理解不是“readbook”的el文件问题。
不知道我啰嗦这么多，作者大大能否明白。如果能解决，就太感谢了。如果不能解决，那就人工切换第四个配置吧。

**Comment by tumashu** [comment]
(setq debug-on-error t) 把结果贴出来

**Comment by tumashu** [comment]
我更新了一下，试试吧

**Comment by HomelandScenery** [comment]
完美解决，太感谢作者大大了。 可以多向你请教私信吗@tumashu

**Comment by tumashu** [comment]
如果是 chinese-fonts-setup 相关的，建议开 issue， 方便共享， 如果是扯淡，花边新闻等不靠谱的，可以私信，这个issue我就关闭了，以后不同的问题最好分开提交 issue，方便查询。
