### ISSUE TITLE
About Apply CFS environment on OSX / CFS 在 osx 上的应用问题 

### ISSUE THREAD

**Issue by cmrshieh** [tumashu/chinese-fonts-setup#33]
// Environment 
OS: osx el capitan  10.11.6 beta
Emacs: Gnu emacs version 24.5.1 release 2015 
Type:  GUI

// Issue description 
   Firstable i followed the README file and done all the steps necessary.
    After package installed by M-x list-package from site melpa . all methods build in CFS
running as normal. and looks good. so install EXT-b font sets. in this case . i'v installed 
HanaMinb as Ext-b english font and simsun as chinese.
    After all steps done above. using  cfs-edit-profile to change the settings in profile1.
reboot emacs a message "chinese-fonts-setup: load "profile1" successfully."  appears below minibuffer.
    but actually there is nothing changed.  

// Work around
    It is strange that after i reboot os x , it works .. everything looks good.
So report this issue for people who use CFS on Os X .  I'v no idea what happend . may be some
Font related stuff i guess .

**Comment by tumashu** [comment]
我听另外一个哥们也遇到过类似的情况，后来他好像重启了一下就OK了，可能是 OSX本身的一些小问题。。。

**Comment by cmrshieh** [comment]
的确如此， 我已经在 gihub 提了 issue .
但是哦 你要确认装一个 ext b 的字体 否则没戏
如果有其他问题 写信给我
呆神现在忙着 健身 啪啪啪 多少让人有点唏嘘 。。

On 5 Jul 2016, at 08:32, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


我听另外一个哥们也遇到过类似的情况，后来他好像重启了一下就OK了，可能是 OSX本身的一些小问题。。。

**Comment by tumashu** [comment]
哈哈，健康生活每一天。。。。。

**Comment by tumashu** [comment]
不过，我也不是离开 emacs， chinese-fonts-setup 和 chinese-pyim 也会一直维护

**Comment by cmrshieh** [comment]
呆神威武啊
希望呆神早日 freelancer 发家致富

On 5 Jul 2016, at 09:21, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


不过，我也不是离开 emacs， chinese-fonts-setup 和 chinese-pyim 也会一直维护

**Comment by cmrshieh** [comment]
尊敬的呆神思密达，
	就是我上午说的问题 ， 我的代码已经写完如下：
为了方便阅读 已经写了很多注释， 但是我有一个问题
当使用 or 来判断给定的  quote-sepatrator 是否为空 然后赋缺省值的时候不没有什么卵用
我测试过 ， 当不使用 interactive  交互的时候 确实有效 但是使用交互的时候 就不管用
这是为什么 ？
       另外 对于  elisp 我不是很熟悉滴说， 呆神看看我的实现是否有问题
是否有更好的办法可以做这件事，另外这是我第一次写信给你请教代码相关的事宜
请多少给点面子 点拨一下，一遍我找点问题 有点进步 继续学习下去 ~ 多谢

							一直关注呆神的 ppt

(defun ppt-auto-quote (&optional quote-sepatrator)
  ; a region should be selected first then 
  ; split it word by word
  ; recreate new string connection words with quota-sepatrator
  (interactive "sWhich Separator :")
  ; if sepatrator is null set default to ","
  (or quote-sepatrator
      (setq  quote-sepatrator ","))
  ; test if a range has beed selected and ensure 
  ; just one line selected
  ; the size of selected region should be fitting the rules as below
  ; R1: lager than 0 mean by that something has been selected
  ; R2: less than the size of current line
  (if (and 
       (> (region-end) (region-beginning))
       (< (- (region-end) (region-beginning)) (- (line-end-position) (line-beginning-position)))
       )
    ; if test is true
    ; means fits rules R1 & R2
      (progn
	(save-excursion
	  ; get the begging & end position of the selected region
	  (setq beg (region-beginning)
		end (region-end))
	  ; get content of selected region
	  (setq str-selected (buffer-substring beg end)
		; split string by word
		str-list-selected (split-string str-selected)
		; new string that we need
		str-quoted ""
		; a index for loop
		list-index 1
		)
	  ; show word of list one by one
	  (dolist (x str-list-selected)
	    ; for last word of list should be no sepatrator followed
	    (if (< list-index (length str-list-selected))
   	      (setq str-quoted (concat str-quoted "\"" x "\"" quote-sepatrator " "))
	      (setq str-quoted (concat str-quoted "\"" x "\" ")))
	      (setq list-index (+ list-index 1))
	    )
	  ; delete region and insert new string
	  (delete-region beg end)
	  (goto-char beg)
	  (insert-string str-quoted)
	  )
	)
    ; if test is false
    ; nothing to do just prompt
    (message "  PM => no region selected"))
)

**Comment by cmrshieh** [comment]
呆神思密达，
       我问题解决了 修改成

(or (> (length quote-sepatrator) 0)
      (setq  quote-sepatrator ","))

看来程序交互之后 string 是有初始值的 只不过是 "" 而不是 null

另外 还请呆神仔细阅读邮件 给点意见 ~~~~~

**Comment by tumashu** [comment]
我做了轻微的改动，你可以参考一下：
```
(defun ppt-auto-quote (&optional quote-sepatrator)
  ;; a region should be selected first then
  ;; split it word by word
  ;; recreate new string connection words with quota-sepatrator
  (interactive)
  ;; if sepatrator is null set default to ","
  (setq quote-sepatrator
        (or quote-sepatrator
            (read-string "Which Separator: " ",")))
  ;; test if a range has beed selected and ensure
  ;; just one line selected
  ;; the size of selected region should be fitting the rules as below
  ;; R1: lager than 0 mean by that something has been selected
  ;; R2: less than the size of current line
  (if (and (> (region-end) (region-beginning))
           (< (- (region-end) (region-beginning))
              (- (line-end-position) (line-beginning-position))))
      ;; if test is true
      ;; means fits rules R1 & R2
      (let* ((beg (region-beginning))
             (end (region-end))
             (string (mapconcat
                      #'(lambda (x)
                          (format "%S" x))
                      (split-string (buffer-substring-no-properties beg end))
                      quote-sepatrator)))
        (save-excursion
          (delete-region beg end)
          (goto-char beg)
          (insert string)))
    ;; if test is false
    ;; nothing to do just prompt
    (message " PM => no region selected")))
```
