### ISSUE TITLE
请求加上spacemacs上的设置方法

### ISSUE THREAD

**Issue by HomelandScenery** [tumashu/chinese-fonts-setup#35]
新人种种不懂，就大大帮助解决一下，spacemacs下，您的packgage已经安装，但不知道如何设置cfs。谢谢了

**Comment by tumashu** [comment]
先照着 README，把README 里面几个命令自己试一下，估计就知道怎么用了， spacemacs 我不太了解，对于 chinese-fonts-setup 来说，好像没啥影响。。。。

**Comment by wduspa** [comment]
spacemacs新建一个layer xx，xx-packages里面增加chinese-fonts-setup，然后xx-init-chinese-fonts-setup，参考readme就可以搞定

**Comment by tumashu** [comment]
这是 spacemace layer 开发者的工作，我记得 spacemace 有一个 chinese layer，你可以联系一下它的维护者，让它添加 chinese-fonts-setup 的相关设置
