### ISSUE TITLE
能否设置行距随着字号自动调整的功能

### ISSUE THREAD

**Issue by HomelandScenery** [tumashu/chinese-fonts-setup#36]
对于我等有大量文字阅读需要的人来说，最希望就是不同的字号下，行距能随之变化。比方，我可以设置行距为字号的1倍~2倍，那么插件的实用性又能提升一个台阶。
请大大考虑能否实现该功能。
另外，听了代码时间中对于大大的访谈，真心觉得大大很萌很可爱，还是非专业程序员，佩服！

**Comment by cmrshieh** [comment]
二呆 经典滴 访谈如下 http://www.lizhi.fm/box#play

**Comment by tumashu** [comment]
我想想看怎么整。。。

**Comment by HomelandScenery** [comment]
辛苦大大了，最好能不同字号对应不同的行距比例，比如14pt 是2倍行距，然后18pt是1.5倍行距，如此类推，不知能否实现，谢谢大大了😄

**Comment by tumashu** [comment]
实现比较简单，但如何和 chinese-fonts-setup 良好集成，则需要好好考虑

**Comment by HomelandScenery** [comment]
在显示表格范例的那个窗口，分别显示英文和中文各一段落文字，在调整字号时同意调整对应的行距。个人愚见供参考，谢谢

**Comment by HomelandScenery** [comment]
还有，既然可以中英文对应不同字号，那么能否或者是否有必要，中英文对应不同的行距？

**Comment by tumashu** [comment]
我研究了一下，你可以试试下面一段代码：
```
(defvar my-line-spacing nil)
(setq my-line-spacing
      '((9  . 0.2)
        (10 . 0.2)
        (11.5 . 0.2)
        (12.5 . 0.2)
        (14 . 0.2)
        (16 . 0.2)
        (18 . 0.2)
        (20 . 0.2)
        (22 . 0.2)
        (24 . 0.2)
        (26 . 0.2)
        (28 . 0.2)
        (30 . 0.2)
        (32 . 0.2)))
(defun my-line-spacing-config (fontsizes-list)
  (let ((english-font-size (car fontsizes-list)))
    (setq-default line-spacing
                  (cdr (assoc english-font-size my-line-spacing)))))
(add-hook 'cfs-set-font-finish-hook #'my-line-spacing-config)
```

**Comment by cmrshieh** [comment]
?
二呆 刚打开邮件   已收到
我先看看

On 16 Jun 2016, at 9:11 AM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


我研究了一下，你可以试试下面一段代码：

(defvar my-line-spacing nil)
(setq my-line-spacing
      '((9  . 0.2)
        (10 . 0.2)
        (11.5 . 0.2)
        (12.5 . 0.2)
        (14 . 0.2)
        (16 . 0.2)
        (18 . 0.2)
        (20 . 0.2)
        (22 . 0.2)
        (24 . 0.2)
        (26 . 0.2)
        (28 . 0.2)
        (30 . 0.2)
        (32 . 0.2)))
(defun my-line-spacing-config (fontsizes-list)
  (let ((english-font-size (car fontsizes-list)))
    (setq-default line-spacing
                  (cdr (assoc english-font-size my-line-spacing)))))
(add-hook 'cfs-set-font-finish-hook #'my-line-spacing-config)

**Comment by cmrshieh** [comment]
以下代码在 mac os 下测试生效
问题是这将导致一个 n x n 的组合
请问二呆 在 emacs 中能实现进度条吗？
如果不能 我赶脚就没有必要实现极简化了
因为这玩意本来就麻烦  .. ^-^

[cid:8EE0A594-D627-4E8B-858C-3E8C86569766@psgateway]
On 16 Jun 2016, at 9:11 AM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


我研究了一下，你可以试试下面一段代码：

(defvar my-line-spacing nil)
(setq my-line-spacing
      '((9  . 0.2)
        (10 . 0.2)
        (11.5 . 0.2)
        (12.5 . 0.2)
        (14 . 0.2)
        (16 . 0.2)
        (18 . 0.2)
        (20 . 0.2)
        (22 . 0.2)
        (24 . 0.2)
        (26 . 0.2)
        (28 . 0.2)
        (30 . 0.2)
        (32 . 0.2)))
(defun my-line-spacing-config (fontsizes-list)
  (let ((english-font-size (car fontsizes-list)))
    (setq-default line-spacing
                  (cdr (assoc english-font-size my-line-spacing)))))
(add-hook 'cfs-set-font-finish-hook #'my-line-spacing-config)

**Comment by tumashu** [comment]
进度条? 不知道， 可能实现吧，不过没有研究过

**Comment by cmrshieh** [comment]
骚瑞二呆大神 我认为我描述的不够清楚
应该是此类东东的  emacs 实现 见下图
[cid:8FF201AC-0B53-4257-B0EF-630B7092A222@psgateway]

就是可以拖动的 然后应用
emacs  实现可以像这样

0.2 ...                1.0
[=|============]
之类 然后快捷键拖拽

想法而已 比较适合行间距 和字体的调节

呆神圣明


On 16 Jun 2016, at 2:27 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


进度条? 不知道， 可能实现吧，不过没有研究过

**Comment by tumashu** [comment]
拖动的话，好像用elisp不太好实现，没有仔细研究过，不过这个点子倒是不错，你可以将这个点子实现，做成一个独立的包。。。。

**Comment by cmrshieh** [comment]
呆神 明显这是开玩乐
我不会啊 。。。
lisp 写过 几百行而已
我找找看看有没有此类的 opensource
问题是 一旦光标到这个位置 就必须 关闭输入 设定只读
请问二呆  对于只读 可以区域性的设定吗？

On 16 Jun 2016, at 4:35 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


拖动的话，好像用elisp不太好实现，没有仔细研究过，不过这个点子倒是不错，你可以将这个点子实现，做成一个独立的包。。。。

**Comment by tumashu** [comment]
虽然我不知道为什么把 这么简单的工作，折腾的这么复杂， 如果是我的话，有不同的字号设置不同的行间距这个功能足够使用了。。。。

**Comment by cmrshieh** [comment]
伴随着易用性的增加 设计难度肯定增加啊
只是个想法 可能有点偏 windows 的教条了

On 16 Jun 2016, at 4:52 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


虽然我不知道为什么把 这么简单的工作，折腾的这么复杂， 如果是我的话，有不同的字号设置不同的行间距这个功能足够使用了。。。。

**Comment by tumashu** [comment]
对于 emacs 来说，也许这并不是易用性的提高， 如果是我，最简单的方式是： 运行一个命令，然后选择一个预定义数字来设定 行间距，一个明明的事情。。。。。

**Comment by tumashu** [comment]
错，最简单的是： 不设。。。。

**Comment by cmrshieh** [comment]
二呆说的很靠谱 符合emacs  的思维和逻辑
实现起来比较简单 赞成
不设置 好吗？ 这是老兄你提出的问题

On 16 Jun 2016, at 5:00 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


错，最简单的是： 不设。。。。

**Comment by tumashu** [comment]
你试试 hydra 吧，绝对符合你的需求
```
(require 'hydra)
(defhydra hydra-line-spacing (global-map "<f2>")
  "Adjust-line-spacing"
  ("j" my-increase-line-spacing "increase")
  ("k" my-decrease-line-spacing "decresae"))

(defun my-increase-line-spacing ()
  (interactive)
  (setq-default
   line-spacing (min (+ (or line-spacing 0) 0.05) 1)))

(defun my-decrease-line-spacing ()
  (interactive)
  (setq-default
   line-spacing (max (- (or line-spacing 0) 0.05) 0.1)))
```

M-x:  hydra-line-spacing/body

**Comment by cmrshieh** [comment]
这个靠谱 感谢呆神

就这么着了

On 16 Jun 2016, at 5:05 PM, paul shieh <paul.shieh@outlook.com<mailto:paul.shieh@outlook.com>> wrote:

二呆说的很靠谱 符合emacs  的思维和逻辑
实现起来比较简单 赞成
不设置 好吗？ 这是老兄你提出的问题

On 16 Jun 2016, at 5:00 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


错，最简单的是： 不设。。。。

**Comment by HomelandScenery** [comment]
两位的论述，末学不懂。只是我的设置有问题吗？好像效果不如预想，还是我不会设置？
11.5和14字号时应该是正常的，但12字号设置不正常，行距太窄了吧，明明设置了1.0的。
![11 5](https://cloud.githubusercontent.com/assets/19407813/16112339/86bdc60e-33e9-11e6-83f1-bdf3b86a836e.png)

12
![12](https://cloud.githubusercontent.com/assets/19407813/16112349/91f78f28-33e9-11e6-8538-41412f15d352.png)

14
![14](https://cloud.githubusercontent.com/assets/19407813/16112360/9ae118fc-33e9-11e6-874c-a69fd65af6e7.png)

新定义的代码
![my line](https://cloud.githubusercontent.com/assets/19407813/16112380/ac562bb8-33e9-11e6-9fb5-ca017c14e51b.png)


设置文件代码
![profile](https://cloud.githubusercontent.com/assets/19407813/16112394/b646f0da-33e9-11e6-8cd9-a15b0d4ff25b.png)

**Comment by cmrshieh** [comment]
兄台可以设置成 20 看看就知道了
1 和 0.5 在我看来没有毛区别啊

On 16 Jun 2016, at 5:43 PM, 故乡风月 <notifications@github.com<mailto:notifications@github.com>> wrote:


两位的论述，末学不懂。只是我的设置有问题吗？好像效果不如预想，还是我不会设置？
11.5和14字号时应该是正常的，但12字号设置不正常，行距太窄了吧，明明设置了1.0的。
[11 5]<https://cloud.githubusercontent.com/assets/19407813/16112339/86bdc60e-33e9-11e6-83f1-bdf3b86a836e.png>

12
[12]<https://cloud.githubusercontent.com/assets/19407813/16112349/91f78f28-33e9-11e6-8538-41412f15d352.png>

14
[14]<https://cloud.githubusercontent.com/assets/19407813/16112360/9ae118fc-33e9-11e6-874c-a69fd65af6e7.png>

新定义的代码
[my line]<https://cloud.githubusercontent.com/assets/19407813/16112380/ac562bb8-33e9-11e6-9fb5-ca017c14e51b.png>

设置文件代码
[profile]<https://cloud.githubusercontent.com/assets/19407813/16112394/b646f0da-33e9-11e6-8cd9-a15b0d4ff25b.png>

**Comment by tumashu** [comment]
我贴的代码对数字有限制，最大不超过1

**Comment by tumashu** [comment]
另外line-spacing 
是一个buffer变量，不小心设置的话，我的代码也可能失效

**Comment by tumashu** [comment]
我明白了，是12 和 12.0的区别

**Comment by cmrshieh** [comment]
我确实 设定很大 但是貌似好用啊

On 16 Jun 2016, at 8:02 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


我明白了，是12 和 12.0的区别

**Comment by tumashu** [comment]
Try this verson:
```
(defvar cfs-line-spacing-alist nil)
(setq cfs-line-spacing-alist
      '((9  . 0.1)
        (10 . 0.9)
        (11.5 . 0.2)
        (12.5 . 0.2)
        (14 . 0.2)
        (16 . 0.2)
        (18 . 0.2)
        (20 . 1.0)
        (22 . 0.2)
        (24 . 0.2)
        (26 . 0.2)
        (28 . 0.2)
        (30 . 0.2)
        (32 . 0.2)))

(defun cfs-line-spacing-setup (fontsizes-list)
  (let ((fontsize (car fontsizes-list))
        (line-spacing-alist (copy-list cfs-line-spacing-alist)))
    (dolist (list line-spacing-alist)
      (when (= fontsize (car list))
        (setq line-spacing-alist nil)
        (setq-default line-spacing (cdr list))))))

(add-hook 'cfs-set-font-finish-hook #'cfs-line-spacing-setup)
```

**Comment by cmrshieh** [comment]
呆神 不打算把这几个函数合并到 cfs 项目里吗？

On 16 Jun 2016, at 9:38 PM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


Try this verson:

(defvar cfs-line-spacing-alist nil)
(setq cfs-line-spacing-alist
      '((9  . 0.1)
        (10 . 0.9)
        (11.5 . 0.2)
        (12.5 . 0.2)
        (14 . 0.2)
        (16 . 0.2)
        (18 . 0.2)
        (20 . 1.0)
        (22 . 0.2)
        (24 . 0.2)
        (26 . 0.2)
        (28 . 0.2)
        (30 . 0.2)
        (32 . 0.2)))

(defun cfs-line-spacing-setup (fontsizes-list)
  (let ((fontsize (car fontsizes-list))
        (line-spacing-alist (copy-list cfs-line-spacing-alist)))
    (dolist (list line-spacing-alist)
      (when (= fontsize (car list))
        (setq line-spacing-alist nil)
        (setq-default line-spacing (cdr list))))))

(add-hook 'cfs-set-font-finish-hook #'cfs-line-spacing-setup)

**Comment by tumashu** [comment]
我暂时不打算将这个功能合并到 chinese-fonts-setup， 你直接拷贝上述代码到你的配置吧。。。。。

**Comment by HomelandScenery** [comment]
真的有效，太感谢大大了，可以的话，加入cfs就完美了！

**Comment by tumashu** [comment]
看需求的人多不多，如果很多的话，可以考虑添加到cfs，这就看你的拉票能力了:-)

**Comment by cmrshieh** [comment]
算了 深知99% 都是伸手党  我已经用上了 赶脚还是
hydra 比较爽 感谢二呆大神

On 17 Jun 2016, at 9:39 AM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


看需求的人多不多，如果很多的话，可以考虑添加到cfs，这就看你的拉票能力了:-)

**Comment by tumashu** [comment]
OK

**Comment by cmrshieh** [comment]
i could't agree more.

On 17 Jun 2016, at 10:05 AM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #36<https://github.com/tumashu/chinese-fonts-setup/issues/36>.

**Comment by cmrshieh** [comment]
算了 深知99% 都是伸手党  我已经用上了 赶脚还是
hydra bi'j
On 17 Jun 2016, at 9:39 AM, tumashu <notifications@github.com<mailto:notifications@github.com>> wrote:


看需求的人多不多，如果很多的话，可以考虑添加到cfs，这就看你的拉票能力了:-)
