### ISSUE TITLE
org-mode粗体斜体无效

### ISSUE THREAD

**Issue by wduspa** [tumashu/chinese-fonts-setup#39]
#34 里面提到了，我的配置文件是自动生成的，我只修改了字体大小，配置如下
去掉chinese-font-setup后，org-mode中粗体，斜体恢复正常
```
;;; `cfs--custom-set-fontsnames' 列表有3个子列表，第1个为英文字体列表，第2个为中文字体列表，
;;; 第3个列表中的字体用于显示不常用汉字，每一个字体列表中，*第一个* *有效并可用* 的字体将被使用。
;;; 将光标移动到上述列表中，按 `C-c C-c' 可以测试字体显示效果。另外，用户可以通过命令
;;; `cfs-insert-fontname’ 来选择一个 *可用* 字体，然后在当前光标处插入其字体名称。
(setq cfs--custom-set-fontnames
      '(
        ("Monaco" "Consolas" "DejaVu Sans Mono" "Droid Sans Mono" "PragmataPro" "Courier" "Courier New" "Liberation Mono" "Ubuntu Mono" "Droid Sans Mono Pro" "Inconsolata" "Source Code Pro" "Lucida Console" "Envy Code R" "Andale Mono" "Lucida Sans Typewriter" "monoOne" "Lucida Typewriter" "Panic Sans" "Hack" "Bitstream Vera Sans Mono" "HyperFont" "PT Mono" "Ti92Pluspc" "Excalibur Monospace" "Menlof" "Cousine" "Fira Mono" "Lekton" "M+ 1mn" "BPmono" "Free Mono" "Anonymous Pro" "ProFont" "ProFontWindows" "Latin Modern Mono" "Code 2002" "ProggyCleanTT" "ProggyTinyTT")
        ("微软雅黑" "Microsoft Yahei" "Microsoft_Yahei" "文泉驿等宽微米黑" "文泉驿等宽正黑" "黑体" "Hiragino Sans GB" "文泉驿正黑" "文泉驿点阵正黑" "SimHei" "SimSun" "NSimSun" "FangSong" "KaiTi" "FangSong_GB2312" "KaiTi_GB2312" "LiSu" "YouYuan" "新宋体" "宋体" "楷体_GB2312" "仿宋_GB2312" "幼圆" "隶书" "STXihei" "STKaiti" "STSong" "STZhongsong" "STFangsong" "FZShuTi" "FZYaoti" "STCaiyun" "STHupo" "STLiti" "STXingkai" "STXinwei" "方正姚体" "方正舒体" "方正粗圆_GBK" "华文仿宋" "华文中宋" "华文彩云" "华文新魏" "华文细黑" "华文行楷")
        ("HanaMinB")
       ))

;;; `cfs--custom-set-fontsizes' 中，所有元素的结构都类似：(英文字号 中文字号 EXT-B字体字号)
;;; 将光标移动到各个数字上，按 C-c C-c 查看光标处字号的对齐效果。
;;; 按 C-<up> 增大光标处字号，按 C-<down> 减小光标处字号。
(setq cfs--custom-set-fontsizes
  '(
     (7     7.5   7.5)
     (9     10.5  10.5)
     (10    12.0  12.0)
     (11.5  13.5  13.5)
     (12.5  15.0  15.0)
     (14    16.5  16.5)
     (16    19.5  19.5)
     (18    21.0  21.0)
     (20    24.0  24.0)
     (22    25.5  25.5)
     (24    28.5  28.5)
     (26    31.5  31.5)
     (28    33.0  33.0)
     (30    36.0  36.0)
     (32    39.0  39.0)
     ))

```

**Comment by tumashu** [comment]
贴出相关截图

在 2016-07-05 11:24:12，"wduspa" <notifications@github.com> 写道：


#34 里面提到了，我的配置文件是自动生成的，我只修改了字体大小，配置如下
去掉chinese-font-setup后，org-mode中粗体，斜体恢复正常

;;; `cfs--custom-set-fontsnames' 列表有3个子列表，第1个为英文字体列表，第2个为中文字体列表，
;;; 第3个列表中的字体用于显示不常用汉字，每一个字体列表中，*第一个* *有效并可用* 的字体将被使用。
;;; 将光标移动到上述列表中，按 `C-c C-c' 可以测试字体显示效果。另外，用户可以通过命令
;;; `cfs-insert-fontname’ 来选择一个 *可用* 字体，然后在当前光标处插入其字体名称。
(setq cfs--custom-set-fontnames
      '(
        ("Monaco" "Consolas" "DejaVu Sans Mono" "Droid Sans Mono" "PragmataPro" "Courier" "Courier New" "Liberation Mono" "Ubuntu Mono" "Droid Sans Mono Pro" "Inconsolata" "Source Code Pro" "Lucida Console" "Envy Code R" "Andale Mono" "Lucida Sans Typewriter" "monoOne" "Lucida Typewriter" "Panic Sans" "Hack" "Bitstream Vera Sans Mono" "HyperFont" "PT Mono" "Ti92Pluspc" "Excalibur Monospace" "Menlof" "Cousine" "Fira Mono" "Lekton" "M+ 1mn" "BPmono" "Free Mono" "Anonymous Pro" "ProFont" "ProFontWindows" "Latin Modern Mono" "Code 2002" "ProggyCleanTT" "ProggyTinyTT")
        ("微软雅黑" "Microsoft Yahei" "Microsoft_Yahei" "文泉驿等宽微米黑" "文泉驿等宽正黑" "黑体" "Hiragino Sans GB" "文泉驿正黑" "文泉驿点阵正黑" "SimHei" "SimSun" "NSimSun" "FangSong" "KaiTi" "FangSong_GB2312" "KaiTi_GB2312" "LiSu" "YouYuan" "新宋体" "宋体" "楷体_GB2312" "仿宋_GB2312" "幼圆" "隶书" "STXihei" "STKaiti" "STSong" "STZhongsong" "STFangsong" "FZShuTi" "FZYaoti" "STCaiyun" "STHupo" "STLiti" "STXingkai" "STXinwei" "方正姚体" "方正舒体" "方正粗圆_GBK" "华文仿宋" "华文中宋" "华文彩云" "华文新魏" "华文细黑" "华文行楷")
        ("HanaMinB")
       ))

;;; `cfs--custom-set-fontsizes' 中，所有元素的结构都类似：(英文字号 中文字号 EXT-B字体字号)
;;; 将光标移动到各个数字上，按 C-c C-c 查看光标处字号的对齐效果。
;;; 按 C-<up> 增大光标处字号，按 C-<down> 减小光标处字号。
(setq cfs--custom-set-fontsizes
  '(
     (7     7.5   7.5)
     (9     10.5  10.5)
     (10    12.0  12.0)
     (11.5  13.5  13.5)
     (12.5  15.0  15.0)
     (14    16.5  16.5)
     (16    19.5  19.5)
     (18    21.0  21.0)
     (20    24.0  24.0)
     (22    25.5  25.5)
     (24    28.5  28.5)
     (26    31.5  31.5)
     (28    33.0  33.0)
     (30    36.0  36.0)
     (32    39.0  39.0)
     ))

**Comment by wduspa** [comment]
如图，org文件和测试buffer都截图了，粗体和斜体没有效果
![cfs-edit](https://cloud.githubusercontent.com/assets/2285126/16587947/8d6231be-42ff-11e6-859c-19691127bf8e.PNG)
![profile](https://cloud.githubusercontent.com/assets/2285126/16587948/902b5902-42ff-11e6-882a-62fbab857e1d.PNG)

**Comment by tumashu** [comment]
Monaco 好像不带粗体，你测试一下：
```
(cl-prettyprint (x-list-fonts "monaco:weight=bold"))
```
你可以使用 修改版 的 monaco-bold：  https://github.com/vjpr/monaco-bold

**Comment by tumashu** [comment]
记得字体名是 Monacob

**Comment by lishuhuakai** [comment]
确实没有效果，按照#34改了之后也没有效果！

**Comment by tumashu** [comment]
chinese-fonts-setup 识别不出 monaco 字体的粗体，可能这个字体本身就没有包含粗体，我提交的补丁做的事情是： 如果找不到 monaco 的粗体，就什么也不做，让 emacs 的字体 fallback 机制来找一个粗体

**Comment by tumashu** [comment]
我刚刚更新了， 你下载最新的代码试试

**Comment by wduspa** [comment]
刚刚更新后搞定了，monaco可以粗体，但是不能斜体，我换了consolas字体就没问题了。中文雅黑可以粗体，没有斜体，估计也是字体的原因，不过斜体一般不用，就不换字体了

**Comment by tumashu** [comment]
monaco 字体很特殊，它的粗体和斜体 x-fonts-list 识别不出来，原因未知, 你可以试试：

```
(cl-prettyprint (x-list-fonts "Monaco"))

```
更新的代码，可以让monaco显示粗体，不过这样折腾，粗体 *可能* 实现不了等宽对齐。。。。
