### ISSUE TITLE
新版 UI 设置界面相关建议

### ISSUE THREAD

**Issue by saccohuo** [tumashu/chinese-fonts-setup#47]
1. 快捷键支持（以下只是举例说明）
  * h键显示快捷键列表和帮助文档
  * 前三个字体设置选项中，支持快捷键选中光标当前行字体（比如空格键）
  * 第四个等宽对齐选项中，支持快捷键应用当前行字体尺寸设置（比如原来的C-c C-c）
  * 第四个等宽对齐选项中，使用 tab 键切换光标到不同字体的字号处，光标到当前行尾部之后自动换行
  * 第四个等宽对齐选项中，支持光标在字号处使用 - 和 = 来加减字号
  * 设置快捷键在四个选项卡之间切换
  * 使用快捷键 r 来刷新 profile 配置 buffer
2. 使用 n 和 p 快捷键需要两次才可以切换一行，最好改为一次切换一行
3. 第四个选项卡中包含调整字体尺寸，却没有在选项卡名称中标注，建议修改个名字
4. 是否可以在配置文件添加某个设置文件，来默认使用或者不使用ui来配置profile

**Comment by tumashu** [comment]
```
前三个字体设置选项中，支持快捷键选中光标当前行字体（比如空格键）
```
这个用 return

```
第四个等宽对齐选项中，支持光标在字号处使用 - 和 = 来加减字号
```
这个功能会添加

```
使用 n 和 p 快捷键需要两次才可以切换一行，最好改为一次切换一行
```
Fixed 

```
第四个等宽对齐选项中，支持快捷键应用当前行字体尺寸设置（比如原来的C-c C-c）
```
这个功能会添加

**Comment by tumashu** [comment]
```
第四个等宽对齐选项中，使用 tab 键切换光标到不同字体的字号处，光标到当前行尾部之后自动换行
```
这个有点难度，暂时不处理

**Comment by saccohuo** [comment]
```
前三个字体设置选项中，支持快捷键选中光标当前行字体（比如空格键）
这个用 return
```
这个功能似乎没有实现。

**Comment by tumashu** [comment]
```
前三个字体设置选项中，支持快捷键选中光标当前行字体（比如空格键）
这个用 return

这个功能似乎没有实现。
```
实现了，可以试试

**Comment by tumashu** [comment]
还有啥想法，没有的话，我就关闭这个issue了

**Comment by saccohuo** [comment]
```
第四个等宽对齐选项中，使用 tab 键切换光标到不同字体的字号处，光标到当前行尾部之后自动换行
这个有点难度，暂时不处理
```
现在那个配置字号的界面似乎是用table的方式实现的，使用tab可以在每一项之间切换，但是不能直接从某一个字号的英文配置的地方循环跳到中文配置的地方，以此类推。这个功能我看应该是可以实现的哎

**Comment by saccohuo** [comment]
```
第四个等宽对齐选项中，支持光标在字号处使用 - 和 = 来加减字号
```
我看你是用 C-↑和C-↓来实现，但是考虑到hhkb上面按方向键不好按，可不可以修改一下

**Comment by tumashu** [comment]
tab那个功能确实不好实现，现在我是没思路，hhkb的问题可以处理

**Comment by tumashu** [comment]
上述两个功能都已经实现

**Comment by saccohuo** [comment]
这两个功能试过了，很好用。
最后一个功能：
```
是否可以在配置文件添加某个设置文件，来默认使用或者不使用 ui 来配置 profile
```
这个实现起来笔记麻烦吗？或者使用一个函数来用ui修改，一个函数直接修改profile（比如cfs-edit-profile-without-ui）呢

**Comment by tumashu** [comment]
分成两个命令倒是很简单

**Comment by saccohuo** [comment]
我又加了一条需求：使用快捷键 r 来刷新 profile 配置 buffer
