### ISSUE TITLE
使用cfs-*-fontsize调整字体的问题

### ISSUE THREAD

**Issue by Yevgnen** [tumashu/chinese-fonts-setup#51]
你好，我在使用`cfs-*-fontsize`调整字体的时候，请问为什么字体会发生变化？

例如：
我的配置

    (set-frame-font
     (font-spec :name "-*-Inconsolata-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                :weight 'normal
                :slant 'normal
                :size 10.0))
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font
       (frame-parameter nil 'font)
       charset
       (font-spec :name "-*-WenQuanYi Micro Hei-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 10.0)))

使用`cfs-increase-fontsize`增加字体大小时，原来使用

    -*-WenQuanYi Micro Hei-normal-normal-normal-*-10-*-*-*-p-0-iso10646-1

的字体
<img width="751" alt="screen shot 2016-08-31 at 19 20 12" src="https://cloud.githubusercontent.com/assets/16749790/18126924/02185416-6fb0-11e6-83e0-60488dc060f3.png">

变成了(变得对不齐了)

    -*-A-OTF Ryumin Pro-normal-normal-normal-*-16-*-*-*-p-0-iso10646-1

即

<img width="748" alt="screen shot 2016-08-31 at 19 20 35" src="https://cloud.githubusercontent.com/assets/16749790/18126938/11d62c02-6fb0-11e6-8b86-2bfd92fb38c0.png">

试过把`chinese-gb2312`也加到`do-list`那个循环也不行。虽然那个`ω`不算是中文，但WenQuanYi好像也有包含了这个字符？为什么调整字体大小的时候它的字体会发生变化呢？请问这个和`chinese-fonts-setup`有关吗？

**Comment by tumashu** [comment]
首先，你使用 chinese-fonts-setup 的方式就有问题，你现在已经使用了自定义配置，那么 cfs 的所有功能就不能使用了。。。。。

**Comment by Yevgnen** [comment]
我只是把自动生成那段截了出来。。我不知道怎么表达我用了的设置。。

**Comment by tumashu** [comment]
那段代码，是给有经验的老用户使用的，这些用户不想依赖 cfs

**Comment by tumashu** [comment]
你把那段代码粘帖到你的配置后，cfs 就没什么作用了，如果你想用 cfs 更改代码，重新粘帖生成的配置片段。。。。。

**Comment by Yevgnen** [comment]
这是我的配置

    (use-package chinese-fonts-setup
      :ensure t
      :bind
      (("C-M-=" . cfs-increase-fontsize)
       ("C-M--" . cfs-decrease-fontsize))
      :init
      (setq cfs-profiles '("program")
            cfs-profiles-directory (expand-file-name "chinese-fonts-setup" private-directory)
            cfs-personal-fontnames '(("Roboto Mono" "Menlo" "Anonymous Pro" "Input" "Iosevka" "Iosevka Slab" "IosevkaCC" "IosevkaCC Slab" "Iosevka Term" "Iosevka Term Slab")
                                     ("FZLanTingHei-L-GBK" "WenQuanYi Micro Hei" "Inziu IosevkaCC SC" "Inziu IosevkaCC TC" "Inziu IosevkaCC J" "Inziu Iosevka SC" "Inziu Iosevka TC" "Inziu Iosevka J" "Inziu IosevkaCC Slab SC" "Inziu IosevkaCC Slab TC" "Inziu IosevkaCC Slab J" "Inziu Iosevka Slab SC" "Inziu Iosevka Slab TC" "Inziu Iosevka Slab J")
                                     ("HanaMinB")))
      :config
      (chinese-fonts-setup-enable)
      (cfs-set-spacemacs-fallback-fonts))
    
我没有用那段代码啊～

**Comment by tumashu** [comment]
运行 cfs-edit-profile 命令

**Comment by Yevgnen** [comment]
运行过了，已经配好，program.el也已经成生好。

**Comment by tumashu** [comment]
那就可以了呀，其他不需要什么配置了。。。。

**Comment by Yevgnen** [comment]
我知道啊。。。然后我就说有上面的问题啊。。晕。

**Comment by tumashu** [comment]
(cfs-set-spacemacs-fallback-fonts) 这个禁用试试

**Comment by tumashu** [comment]
关键是： -*-A-OTF Ryumin Pro-normal-normal-normal-*-16-*-*-*-p-0-iso10646-1 这个字体从哪来的，cfs里面和你的配置里面都没有呀？

**Comment by Yevgnen** [comment]
我的配置里面没有，就是不知道调整大小的时候fallback了？

**Comment by tumashu** [comment]
不可能吧，按照cfs的搜索机制，那末多内置的字体,不可能一个都不存在呀。。。。。

**Comment by tumashu** [comment]
(cfs--get-valid-fonts) 这个的结果是啥？

**Comment by Yevgnen** [comment]
调整字体大小的时候也要重新搜索？

**Comment by Yevgnen** [comment]
结果：("-*-Inconsolata-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1" "-*-WenQuanYi Micro Hei-normal-normal-normal-*-*-*-*-*-p-0-iso10646-1" "-*-HanaMinB-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1")

**Comment by tumashu** [comment]
对呀，你有其它字体配置和 cfs 冲突吧？

**Comment by Yevgnen** [comment]
没有～

**Comment by tumashu** [comment]
换一个其他英文字体试试，看看是不是也存在这个问题

**Comment by Yevgnen** [comment]
顺便说一个不知道是不是问题的问题，字体名有“-”的时候例如("FZLanTingHei-L-GBK")，`cfs-personal-fontnames`好像识别不了？

**Comment by tumashu** [comment]
恩，有这个问题，但应该可以使用。。。。

**Comment by tumashu** [comment]
我猜测，可能是你用的字体不包含那些符号，所以emacs启用了字体fallback机制，因为cfs不处理符号字体

**Comment by tumashu** [comment]
你找一个字符全的英文字体测试一下，看看是不是这个问题

**Comment by Yevgnen** [comment]
全英文应该没什么问题吧。可是10号字的时候不是说wenquanyi包含了这些字符？我试了用menu bar的时界面去设字体大小，这个时候倒什么问题。。

**Comment by tumashu** [comment]
cfs 只设置中文，没设置符号字体呀。。。。

**Comment by tumashu** [comment]
你用这个 hook 试试，看能不能调整 符号字体
```
(defun my-set-symbol-fonts (fontsizes-list)
  (set-fontset-font t 'symbol "Inconsolata" nil 'append))

(add-hook 'cfs-set-font-finish-hook 'my-set-symbol-fonts)

```

**Comment by Yevgnen** [comment]
应该是"WenQuanYi Micro Hei"，是可。但是我试过在源码里设置中文那个`dolist`里直接加入`symbol`是不行的。。或者只使用模板代码加入`symbol`也不行。

我下午写了个类似的，不过加到了`greek-iso8859-7`里面，也可。

就是不明白要特别另外在hook里设一次才行。。可能我是个案吧。
