### ISSUE TITLE
新版之后，有的中文字体无法随英文字号变化。

### ISSUE THREAD

**Issue by SyrakuShaikh** [tumashu/chinese-fonts-setup#53]
我用的是最新版的Spacemacs，Emacs是25.1版本，系统是Archlinux。

用以前版本（v3？）的Chinese-Fonts-Setup（以下简称cfs）的时候，在org-mode下，不同的标题字号是不一样的。中文字体可以和英文字体一样，在不同级别的标题上，显示为不同的字号。

今天更新新版（v4？）的cfs之后，对齐和以前一样没问题，可是org-mode的标题却出问题了。。。
不管是什么级别的标题，中文字体都是和正文一样大小，但是由于英文字体是随着标题的级别不同而改变字号的，所以就显得特别别扭，而且本来就应该随着标题的级别不同而自动改变字号。

我测试了一些其他字体，思源黑体也不行，文泉驿也不行，方正兰亭黑也不行，只有冬青黑体可以。

方便的话，请作者你测试一下，谢谢。

**Comment by tumashu** [comment]
我知道这个问题，cfs有一个变量，名称中包含rescale ，将这个变量设置为t，就可以实现你需要的

**Comment by tumashu** [comment]
不过有archlinux的同学反应，开启这个功能后，等宽功能会出问题，你可以试试。。。。

**Comment by SyrakuShaikh** [comment]
试过了，是`cfs-use-face-font-rescale`。在我的系统下，没问题。

反映另一个问题：图形化界面下，“对齐”这一个栏目（标签）下，字号的这几行是固定的，比如说适合我的字号是英文15，里面就没有，如果我直接在profile里更改，也不会在图形化界面下生效，当然也不是什么大事，反正可以直接在.emacs文件里自己设置。

**Comment by tumashu** [comment]
如果你需要15号字体，我倒是可以添加

**Comment by tumashu** [comment]
最新版我已经添加了15号字体，你如果想用，需要使用cfs-regenerate-profile强制升级profile

**Comment by SyrakuShaikh** [comment]
@tumashu 好的，谢谢

**Comment by tumashu** [comment]
不客气
