### ISSUE TITLE
Unicode 扩充a字体在某些情况下无法正常显示

### ISSUE THREAD

**Issue by HomelandScenery** [tumashu/chinese-fonts-setup#54]
非常感谢作者的插件。目前遇到一些疑问，当我使用“方正兰亭黑_GBK”字体作为中文主要字体后，当遇到unicode 扩充a字体（中日韩统一表意文字扩展A），不能正常显示。只有使用其他包含有相对应的扩充A字体的字体文件时（如微软雅黑、楷体），才能正常显示扩充A文字，请问如何解决？能否对扩充A文字单独设置一个字体（如HanaMinA.ttf）？

操作环境：Windows10，GNU Emacs 25.0.94.2 (x86_64-w64-mingw32) 
![screenshot - 2016_9_8 22_21_10](https://cloud.githubusercontent.com/assets/19407813/18353318/1d1020f4-7614-11e6-9364-91d7d300a34d.png)

![screenshot - 2016_9_8 22_21_34](https://cloud.githubusercontent.com/assets/19407813/18353327/2369739c-7614-11e6-87d6-2b51b42005e9.png)

**Comment by tumashu** [comment]
这个，你在 EXT-B字体 里面添加设置一个试试，看行不行






在 2016-09-08 22:39:02，"故乡风月" <notifications@github.com> 写道：


非常感谢作者的插件。目前遇到一些疑问，当我使用“方正兰亭黑_GBK”字体作为中文主要字体后，当遇到unicode 扩充a字体（中日韩统一表意文字扩展A），不能正常显示。只有使用其他包含有相对应的扩充A字体的字体文件时（如微软雅黑、楷体），才能正常显示扩充A文字，请问如何解决？能否对扩充A文字单独设置一个字体（如HanaMinA.ttf）？

操作环境：Windows10，GNU Emacs 25.0.94.2 (x86_64-w64-mingw32)

**Comment by HomelandScenery** [comment]
请问我应该如何设置呢。我的ext-b字体（见附图红色划线）能够正常显示，某些ext-a字体（见附图黄色划线）能显示，但大小似乎有点问题。
![ext-b](https://cloud.githubusercontent.com/assets/19407813/18375080/3ed304ec-7685-11e6-929e-4ab3dec2bdb3.PNG)

![ext-b2](https://cloud.githubusercontent.com/assets/19407813/18375082/44494ca6-7685-11e6-83b3-a16d2a448f3b.PNG)

**Comment by tumashu** [comment]
你为什么一定要使用这个字体呢，换一个其他字体不可以吗？ 如果一定要使用这个字体，可能的方式是，但下面的代码我没有测试。。。。
```
(defun my-set-ext-a-fonts (fontsizes-list)
  (set-fontset-font
   "fontset-default" nil
   (font-spec :name "一个EXTA字体"
              :size (nth 1 fontsizes-list)
              :weight 'normal
              :slant 'normal)
   nil 'prepend))

(add-hook 'cfs-set-font-finish-hook 'my-set-ext-a-fonts)
```

**Comment by tumashu** [comment]
另外吐槽一句： 你的兴趣好高大上。。。。。。

**Comment by HomelandScenery** [comment]
多谢大大，已经测试成功。特别好的地方是，如果当前字体（如楷体）包含ext-a字形的，则不会改变当前字体（即维持楷体），否则就应用代码中相应字体。如无意外，可以关闭了。

另：请别吐槽：）
```
;;测试ext-a字体;;;;;
(defun cfs-set-ext-a-fonts (fontsizes-list)
  (set-fontset-font
   "fontset-default" nil
   (font-spec :name "HanaMinA"
              :size (nth 1 fontsizes-list)
              :weight 'normal
              :slant 'normal)
   nil 'prepend))

(add-hook 'cfs-set-font-finish-hook 'cfs-set-ext-a-fonts)
```

**Comment by tumashu** [comment]
有可能，因为ext-b也是用prepend设置的，也许你应该在hook中，强制设置exta部分的字体，具体怎么整，我也不知道。。。。

**Comment by tumashu** [comment]
我估计你应该类似下面的设置：  (#x24b6 . #x24fe) 需要你改成 exta 的范围，具体怎么改，我对此不太了解。
```
(defun cfs-set-ext-a-fonts (fontsizes-list)
  (set-fontset-font
   "fontset-default" '(#x24b6 . #x24fe)
   (font-spec :name "HanaMinA"
              :size (nth 1 fontsizes-list)
              :weight 'normal
              :slant 'normal)
   nil 'prepend))

(add-hook 'cfs-set-font-finish-hook 'cfs-set-ext-a-fonts)

```

**Comment by tumashu** [comment]
我找到了，你运行 (list-fontsets t) 就可以弹出一个buffer，那里面就分成许多区域，自己找找

**Comment by HomelandScenery** [comment]
我输入了以下代码，```"fontset-default" '(#x3400 . #x4DB5)```，仍然不能正常认别。

```(list-fontsets t)``运行后，看不懂应该输入哪 个范围。 

```emacs-lisp
(defun cfs-set-ext-a-fonts (fontsizes-list)
  (set-fontset-font
   "fontset-default" '(#x3400 . #x4DB5)
   (font-spec :name "HanaMinA"
              :size (nth 1 fontsizes-list)
              :weight 'normal
              :slant 'normal)
   nil 'prepend))

(add-hook 'cfs-set-font-finish-hook 'cfs-set-ext-a-fonts)
```

**Comment by tumashu** [comment]
我也搞不清楚是哪个范围，底层的东西，不太明白，实在不行，找一个其他字体用吧，省事

**Comment by tumashu** [comment]
试试下面的的代码：
```
(defun cfs-set-ext-a-fonts (fontsizes-list)
  (set-fontset-font
   "fontset-default" '(#x3400 . #x4DFF)
   (font-spec :name "微软雅黑"
              :size (nth 2 fontsizes-list)
              :weight 'normal
              :slant 'normal)
   nil))

(add-hook 'cfs-set-font-finish-hook 'cfs-set-ext-a-fonts)

```

**Comment by tumashu** [comment]
![_021](https://cloud.githubusercontent.com/assets/67725/18405540/5597945e-7725-11e6-80d0-b808b10ef680.png)

**Comment by tumashu** [comment]
按红线部分，你可以了解unicode-bmb 汉字的分布

**Comment by HomelandScenery** [comment]
运行了`describe-char`命令，但是` code point in charset `没有能链接点击的帮助。

**Comment by tumashu** [comment]
你选择的字符不是 unicode-bmp 范围内吧？

**Comment by HomelandScenery** [comment]
成功了，我觉得可以说能打95分，可否有进步的空间。
原来的代码有个好处：如果当前字体（如楷体）包含ext-a字形的，则不会改变当前字体（即维持楷体），否则就应用代码中相应字体。
这次版本，固定死ext-a字形使用某种字体，所以我觉得是否还能再提升。
![ext-a_3](https://cloud.githubusercontent.com/assets/19407813/18406241/1e0bcf66-772d-11e6-9ed6-add2ff359376.PNG)

**Comment by tumashu** [comment]
这个你可以通过调整 那个范围来实现， 你只要设置楷体不包含的字符的范围 不就可以了，可以设置一个比较小的范围的

**Comment by tumashu** [comment]
另外一种方式，就是使用 append 或者 prepend 参数，和 字符范围配合，应该可以实现你需要的功能

**Comment by HomelandScenery** [comment]
我明明选了”䀹“这个字阿，其他的字是可以的

**Comment by tumashu** [comment]
测试这个
```
(defun my-set-exta-fonts (fontsizes-list)
  (let* ((fontname "微软雅黑")
         (fontsize (nth 2 fontsizes-list))
         (fontspec (font-spec :name fontname
                              :size fontsize
                              :weight 'normal
                              :slant 'normal)))
    (if (cfs--fontspec-valid-p fontspec)
        (set-fontset-font "fontset-default" '(#x3400 . #x4DFF) fontspec nil 'append) ;; 另外测试 prepend
      (message "字体 %S 不存在！" fontname))))

(add-hook 'cfs-set-font-finish-hook 'my-set-exta-fonts)

```

**Comment by HomelandScenery** [comment]
两个都试过，都不行，维持使用"微软雅黑"

**Comment by tumashu** [comment]
不可能吧，我这里测试可以的呀？

**Comment by tumashu** [comment]
![_022](https://cloud.githubusercontent.com/assets/67725/18406478/ecee82d6-772f-11e6-94e7-2ebd2f19dd2e.png)

**Comment by tumashu** [comment]
你说的是这意思吧？

**Comment by HomelandScenery** [comment]
![ext-a_4](https://cloud.githubusercontent.com/assets/19407813/18406547/e5b3fd06-7730-11e6-9212-54579a814e3f.PNG)
![ext-a_5](https://cloud.githubusercontent.com/assets/19407813/18406548/e81c0f7a-7730-11e6-90f7-5c84f7695de2.PNG)

**Comment by tumashu** [comment]
我觉得是，你默认的中文字体，没有那个字吧？

**Comment by tumashu** [comment]
另外，重启一下 emacs 试试

**Comment by HomelandScenery** [comment]
1.楷体是有”䀹“字能正常显示的。
2.每次测试都重启了emacs

**Comment by tumashu** [comment]
我这里，楷体不能显示，因为 cfs 里面的楷体是： 楷体-gb2312

**Comment by tumashu** [comment]
AR PL UKai CN 可以显示这个字

**Comment by HomelandScenery** [comment]
![ext-a_6](https://cloud.githubusercontent.com/assets/19407813/18407306/1b318fda-773f-11e6-825d-e797a1b9bf81.PNG)
![ext-a_7](https://cloud.githubusercontent.com/assets/19407813/18407307/1ddf607c-773f-11e6-9d57-7b63e9ebb36e.PNG)

```emacs-lisp
'append) ;; 另外测试 append也测试过了 
```

**Comment by tumashu** [comment]
你让 那个字体 显示为楷体，然后 describe-char ，看看什么字体，我测试了许多楷体，可惜，没有一个能显示这个字

**Comment by HomelandScenery** [comment]
```
       position: 13 of 18 (67%), column: 0
            character: 䀹 (displayed as 䀹) (codepoint 16441, #o40071, #x4039)
    preferred charset: unicode (Unicode (ISO10646))
code point in charset: 0x4039
               script: han
               syntax: w 	which means: word
             category: .:Base, C:2-byte han, L:Left-to-right (strong), c:Chinese, j:Japanese, |:line breakable
             to input: type "C-x 8 RET 4039"
          buffer code: #xE4 #x80 #xB9
            file code: #xE4 #x80 #xB9 (encoded by coding system utf-8-dos)
              display: by this font (glyph code)
    uniscribe:-outline-楷体-normal-normal-normal-mono-26-*-*-*-c-*-iso10646-1 (#x6215)

Character code properties: customize what to show
  name: CJK IDEOGRAPH-4039
  general-category: Lo (Letter, Other)
  decomposition: (16441) ('䀹')

There are text properties here:
  fontified            t
  line-prefix          ""
  wrap-prefix          ""

```
北京中易中标电子信息技术有限公司 
© Beijing ZhongYi Electronics Co., 1995-2005, All rights reserved

**Comment by tumashu** [comment]
我在这里测试了一下，我这里可以

**Comment by tumashu** [comment]
![_024](https://cloud.githubusercontent.com/assets/67725/18410948/e9334cc4-779f-11e6-8d26-5fa232001a86.png)

**Comment by tumashu** [comment]
![_025](https://cloud.githubusercontent.com/assets/67725/18410960/16fe1f4e-77a0-11e6-966a-3aeba0635975.png)

**Comment by tumashu** [comment]
你是用的 spacemacs 吗？ 有没有开启spacemacs fallback 字体支持？ (cfs-set-spacemacs-fallback-fonts)，禁用试试

**Comment by HomelandScenery** [comment]
是的，我在用spacemacs，已经禁用了` (cfs-set-spacemacs-fallback-fonts)`，但还是维持不变没有效果，仍然统一为“微软雅黑”。十分感谢大大，已经解决了大问题，小细节就留待日后改善吧。

**Comment by tumashu** [comment]
好吧，我这里没问题，不知道你那边为什么会出现问题。。。。。

**Comment by tumashu** [comment]
这个就暂时关闭了。。。。

**Comment by HomelandScenery** [comment]
为什么我的 describe-char 显示` preferred charset: unicode (Unicode (ISO10646))`，而您的是`unicode bmp`

**Comment by tumashu** [comment]
我不知道，我默认coding 是 utf-8-unix ，也许和这个有关系

**Comment by HomelandScenery** [comment]
```emacs-lisp
 (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (setq file-name-coding-system 'gbk)
```
大大，我是这样设置的，您的设置可以贴出来吗

**Comment by tumashu** [comment]
https://github.com/tumashu/emacs-helper/blob/master/eh-basic.el  另外，你也可以先禁用 spacemacs，使用纯emacs 来测试一下，spacemacs 太庞大了，不知道里面是不是有一些特殊的设置

**Comment by HomelandScenery** [comment]
先谢一个，现在工作，日后继续测试，感谢！

**Comment by tumashu** [comment]
恩，这个问题先暂时就到这吧。。。。

**Comment by HomelandScenery** [comment]
成功了，使用了大大的配置，终于得到想要的结果
```emacs-lisp
;; Charset 设置
(use-package mule
  :ensure nil
  :config

  (set-language-environment "UTF-8")
  (set-buffer-file-coding-system 'utf-8-unix)
  (set-clipboard-coding-system 'utf-8-unix)
  (set-file-name-coding-system 'utf-8-unix)
  (set-keyboard-coding-system 'utf-8-unix)
  (set-next-selection-coding-system 'utf-8-unix)
  (set-selection-coding-system 'utf-8-unix)
  (set-terminal-coding-system 'utf-8-unix)

  (when (eq system-type 'windows-nt)
    (set-selection-coding-system 'gbk-dos)
    (set-next-selection-coding-system 'gbk-dos)
    (set-clipboard-coding-system 'gbk-dos)))
```

![exta_8](https://cloud.githubusercontent.com/assets/19407813/18423075/3004370a-78d4-11e6-92e9-f5e4ffb1fa46.PNG)

**Comment by tumashu** [comment]
这个问题确实有点诡异。。。。

**Comment by tumashu** [comment]
一个可能的问题是： 你当前的 EXTB字体名称不在列表里面：         ("HanaMinB" "SimSun-ExtB" "MingLiU-ExtB" "PMingLiU-ExtB" "MingLiU_HKSCS-ExtB")

有时候，相同的字体在不同的系统里面，字体名称是不一样的

**Comment by tumashu** [comment]
用 cnfonts-insert-fontname 可以查看查看

**Comment by RickLeaf** [comment]
cnfonts-insert-fontname 的确是有 HanaMinB 的，我同时也安装了HanaMinA，好像改哪个都没有用。

**Comment by RickLeaf** [comment]
不知道是不是和coding有关系，我关闭其他配置看看

**Comment by tumashu** [comment]
用 emacs -Q 测试一下，看是不是其他地方的配置覆盖了cnfonts的设置了

**Comment by RickLeaf** [comment]
没太懂，用emacs -Q怎么测试啊

**Comment by RickLeaf** [comment]
好在26版本工作已经正常了
