### ISSUE TITLE
根据system-type来使用相应的profile

### ISSUE THREAD

**Issue by liuxueyang** [tumashu/chinese-fonts-setup#55]
谢谢你的插件！
请问如何根据system-type来设置插件使用对应的profile呢？而不用每次在不同的系统里面需要手动switch-profile

**Comment by tumashu** [comment]
这个问题挺有意思，你是不是自己管理profile?

**Comment by tumashu** [comment]
设置  cfs-use-system-type 为 t 就可以了

**Comment by liuxueyang** [comment]
是的，我在不同的操作系統裏面使用不同的Profile
你測試後可以工作麼？我這裏好像並不可以正常工作，難道是我設置不對？

順便問一下，更新之後大概多長時間之後melpa之後會同步你的更新呢？

**Comment by tumashu** [comment]
一般四个小时以上吧，我添加的功能和你理解的不太一样，我添加的功能是: 同一个profile，在不同的操作系统下，其保存的目录不同

**Comment by liuxueyang** [comment]
原來是這樣，這個方案更好。謝謝！
