### ISSUE TITLE
让chinese-fonts-setup设置的字号只在org下启用

### ISSUE THREAD

**Issue by seventhking** [tumashu/chinese-fonts-setup#56]
不知应该如何配置 - -，能给个例子吗？

**Comment by saccohuo** [comment]
按照这个需求，在不同的buffer之间切换的时候，字体和字号也要跟随着切换？

**Comment by tumashu** [comment]
啥意思？能说的具体一点吗？

**Comment by seventhking** [comment]
我的需求是，现在在org-mode下，中英文导致table不对齐，而我使用chinese-fonts-setup调节字号大小后，字号会比较大，这在写代码的时候不方便。
不知道可不可以当buffer模式是org-mode的时候，启用一个profile，不是org-mode的时候，使用emacs原有的字体字号配置。或者有更好的办法解决table不对齐的问题。

麻烦各位了。

**Comment by tumashu** [comment]
chinese-fonts-setup的基本概念你没有理解，你用的命令是增大字号的命令，对齐设置用cfs-edit-profile， 对齐设置后，9 - 32 范围的字号都可以对齐，你选一个合适的字号用就可以
