### ISSUE TITLE
 关于customize-save-variable

### ISSUE THREAD

**Issue by seagle0128** [tumashu/chinese-fonts-setup#57]
您好。cfs很方便很实用，提个建议，能否不要每次切换profile都保存变量，或者给个选项控制。个人用use-package 来管理所有包，init.el用github同步，每次都会修改init文件很是烦恼。
谢谢！

**Comment by tumashu** [comment]
如果，没有保存这些信息，cfs的功能就残废了，我感觉。

**Comment by tumashu** [comment]
关键是，你为什么频繁切换 profile 呢？

**Comment by seagle0128** [comment]
比如，有时候我只是想临时切换到另外一个profile看篇文章而已，字体选择比较大，但不需要保存。

**Comment by tumashu** [comment]
我研究研究再说吧，看有什么好方法

**Comment by seagle0128** [comment]
谢谢！

**Comment by tumashu** [comment]
我研究了一下代码，要实现你所需要的功能，需要对代码做很大的改动，难度很大，也许你可以通过设置： custom-file 将这部分代码独立出来，不用git管理。

**Comment by tumashu** [comment]
也许可以解决，我在试试

**Comment by tumashu** [comment]
等更新后，设置：
```
(setq cfs-save-current-profile nil)
```
就可以了。

**Comment by seagle0128** [comment]
多谢，已经可以啦

**Comment by tangxinfa** [comment]
(setq cfs-save-current-profile nil)

----- 太赞了。

我也有类似需求，平时用小字体，但有时会用大字体，这个其实和当前的 mode 相关（如：writeroom-mode 看文章会用大字体，而做演示时或多人盯着屏幕计解时会用超大字体），目前只能设置全局的字体，能够快速切换也可以满足需求。

**Comment by tumashu** [comment]
感谢大家的反馈：-）
