### ISSUE TITLE
mac下如何保持系统默认的字体

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [tumashu/chinese-fonts-setup#58]
发现对齐后的字体没有原先默认的好看
但是又找不到原先默认的字体是什么

**Comment by tumashu** [comment]
cfs-insert-fontname 可以在当前 buffer 中插入一个系统存在的字体名称

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
emacs 可以直接查看当前的字体名称嘛

**Comment by tumashu** [comment]
有时候，两者是不完全一样滴

**Comment by tumashu** [comment]
```
但是又找不到原先默认的字体是什么
```
虽然我还没太明白你这句话是什么意思，是让 cfs 找呢，还是其他意思， cfs 只是内置常用的一些字体名称，没有内置的字体是无法识别的。。。。

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
最好是保持默认字体不变 
直接中英文对齐

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
可以直接设置字体宽度达到对齐的效果嘛
求指教

**Comment by tumashu** [comment]
英文字体和中文字体都确定了，才有可能对齐，你找到你想要的字体，让cfs对齐是可以的

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
感谢耐心回答 首页上写的很清楚了

**Comment by tumashu** [comment]
如果用户需要在自己的 emacs 配置中管理一些个人字体，可以使用变量 `cfs-personal-fontnames' , 其结构与 `cfs–fontnames-fallback'一样。

**Comment by tumashu** [comment]
设置 cfs-personal-fontnames 后，再在cfs界面中选择就可以了

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
好像没效果
`(setq cfs-personal-fontnames`
`      '(("Helvetica")))`

**Comment by tumashu** [comment]
我这里不报错，你重启一下 emacs 试试

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
但是cfs界面找不到那个字体

**Comment by tumashu** [comment]
我这里可以找到，个人字体 都有 “P” 标记，你可以搜索一下试试

**Comment by tumashu** [comment]
![- 2016 10 08 - 19 59 55](https://cloud.githubusercontent.com/assets/67725/19213050/f203e4bc-8d93-11e6-8082-a8f95c95ae40.png)

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
支持最新版本25.1嘛

**Comment by tumashu** [comment]
那当然了。

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
> 你可以搜索一下试试
可以手动搜索

**Comment by tumashu** [comment]
你找前面带 "P" 的不就得了。。。

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
看下你那边的设置

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
总结一下 
## first
`M-x cfs-edit-profile-without-ui`
## second
 根据提示在 `cfs--custom-set-fontnames` 下用 `M-x cfs-insert-fonts` 插入想要的字体

## 楼主的回答完美的解决了我的问题

**Comment by tumashu** [comment]
恩，字体这东西，个人感觉很重要。。。。。这个issue我关了
