### ISSUE TITLE
org文件的标题和正文可以设置为不同字体吗？

### ISSUE THREAD

**Issue by ziyuanjun** [tumashu/chinese-fonts-setup#59]
我用`cfs-edit-profile`设置，发现中文只能唯一选择一种字体，这使得整个org文件标题和正文都是同样的字体。
文档介绍了可以使用`(setq cfs-use-face-font-rescale t)`把大小设置成不一样的，请问想把字体设置成不一样的该怎么做呢？

**Comment by tumashu** [comment]
这个估计要设置org的相关的face

**Comment by tumashu** [comment]
这个issue关闭了
