### ISSUE TITLE
关于中英文同时缩放的设置

### ISSUE THREAD

**Issue by MagisDing** [tumashu/chinese-fonts-setup#60]
1.用cfs-edit-profile设置好之后自定义字体，中英文字体可以同时缩放，但是缩放之后并不能保证对齐，说明我之前的误差只是在设置分辨率下肉眼不易察觉，请问这个问题有解么？
2.另外如果用“其他”生成的代码不能实现中英文字体同时缩放，请问还需要添加什么？

**Comment by tumashu** [comment]
cfs-edit-profile 里面有一个对齐页面，在那里设置对齐，“其他” 那段代码是给那些不想以来 cfs 的老鸟用的，只是把当前的 cfs 设置转为一段elisp 代码而已

**Comment by tumashu** [comment]
依赖

**Comment by MagisDing** [comment]
明白，那么如果要实现中英文同时缩放的代码改如何添加，如果想用他们来代替整个Package的话。

**Comment by tumashu** [comment]
就是把这个package的功能在你的 .emacs 里面重写实现一遍：-）

**Comment by tumashu** [comment]
这个ｉｓｓｕｅ关闭了
