### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by yyangdid** [tumashu/chinese-fonts-setup#61]
有办法设置为下面这样么？
在编辑org文件的时候使用中英等宽的profile2，在切换到其他buffer编辑python文件的时候不使用中英等宽

**Comment by tumashu** [comment]
可以是可以，不过未必好用，用hook来切换profile

**Comment by lxeg0429** [comment]
这个要怎么实现啊？

**Comment by tumashu** [comment]
cfs有一个专门的命令来切换profile，你可以把这个命令包装一下，加到switch buffer的hook里，不就可以了，具体实现你需要查找相关hook的文档了

**Comment by lxeg0429** [comment]
哦，应该是可以的，不过那样好像会对emacs的窗口大小有影响。还是算了吧。

**Comment by tumashu** [comment]
这个ｉｓｓｕｅ关闭了．．．
