### ISSUE TITLE
New frame 字体大小改变

### ISSUE THREAD

**Issue by zhixing2017** [tumashu/chinese-fonts-setup#65]
`M-x new frame`，新窗口的字体改变，这个要怎么解决啊？
`On GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-16, Windows 7 64bit.`

**Comment by tumashu** [comment]
没明白你说的是什么意思

**Comment by zhixing2017** [comment]
设置好字体后，Emacs的字体显示没有问题。`M-x new frame`之后，会新开一个窗口，这时字体的显示与设置的不一样了，变小了。重新`switch`到`cfs设置的文件`之后才会显示原来的。

**Comment by tumashu** [comment]
最好给我发一个截图, 我这里还是不太理解

**Comment by yangsheng6810** [comment]
似乎新出的frame不会自动设置字体，我是这么解决的：
```emacs-lisp
  (use-package chinese-fonts-setup)

  (defun my-after-frame-function ()
    ;; 让 chinese-fonts-setup 随着 emacs 自动生效。
    (chinese-fonts-setup-enable)
    ;; 让 spacemacs mode-line 中的 Unicode 图标正确显示。
    (cfs-set-spacemacs-fallback-fonts)
    )
  (my-after-frame-function)
  (add-hook 'after-make-frame-functions
            '(lambda (f)
               (my-after-frame-function)
               ))
```

**Comment by tumashu** [comment]
```
(defun chinese-fonts-setup-enable ()
  "运行这个函数，可以让 emacs 启动的时候就激活 chinese-fonts-setup."
  (interactive)
  (setq cfs--enabled-p t)
  (if (and (fboundp 'daemonp) (daemonp))
      (add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
    (add-hook 'window-setup-hook #'cfs-set-font-with-saved-step)))

```

**Comment by tumashu** [comment]
或许我应该调整一下这个函数

**Comment by tumashu** [comment]
```
    ;; 让 spacemacs mode-line 中的 Unicode 图标正确显示。
    (cfs-set-spacemacs-fallback-fonts)
```
这个设置有效吗, 我不用 spacemacs, 所以这个我自己从来没有测试过 :-)

**Comment by zhixing2017** [comment]
我试了上面的两种方法，没有生效，不知道是什么原因。
我的mode-line里没有特别的图标，所以那个设置对我没用。
下面是我的截图：
![default](https://cloud.githubusercontent.com/assets/26316963/25300463/a1ced4cc-2742-11e7-8a81-fbbd87877dd9.png)

**Comment by tumashu** [comment]
```
(defun chinese-fonts-setup-enable ()
  "运行这个函数，可以让 emacs 启动的时候就激活 chinese-fonts-setup."
  (interactive)
  (setq cfs--enabled-p t)
  (add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
  (add-hook 'window-setup-hook #'cfs-set-font-with-saved-step))
```

**Comment by tumashu** [comment]
试试这个行不行

**Comment by yangsheng6810** [comment]
我也没找到有什么区别。我的modeline就多一些带圈字母，但是加不加那句命令都一样。因为只有当前窗口才能显示，所以给不了对比截图。

**Comment by zhixing2017** [comment]
试了一下，没有效果

**Comment by tumashu** [comment]
赞!

**Comment by tumashu** [comment]
这个issue我就关闭了...

**Comment by yangsheng6810** [comment]
为解决另一个issue而读了一下spacemacs的代码，问题发生的原因是spacemacs在`default-frame-alist`里设置了默认字体，这样在新的frame创建之后会根据`default-frame-alist`来设置frame的长宽和字体，而cfs的设置就会被覆盖，需要重新enable。
原来的代码里判断emacs是不是跑在daemon mode下，如果是才`add-hook`。而新frame除了在daemon mode下会出现，还会在`(new-frame)`时出现。这时如果没有设置`default-frame-alist`，那新的frame可能会沿用之前的字体设定，一切OK；如果设置了`default-frame-alist`，就需要重新enable了。
总结一下，可能`add-hook`时，不应该判断是不是daemon mode，毕竟完全有可能在enable了cfs之后使用`(server-start)`来启动server。判断是不是daemon mode有什么其他的目的吗？

**Comment by tumashu** [comment]
```
  (add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
  (add-hook 'window-setup-hook #'cfs-set-font-with-saved-step)
```
那时候我就简单的想, 非daemon使用 window-setup-hook, daemon 使用 after-make-frame-functions, 
我现在不太了解两个语句同时出现, 会不会冲突, 没有冲突的话, 就很简单了.

**Comment by tumashu** [comment]
我查了一下文档, 估计冲突的可能性不大.... 两个hook同时挂上的话,估计不会出问题了吧
