### ISSUE TITLE
setq cfs-profiles 导致英文字体变成斜体

### ISSUE THREAD

**Issue by tendant** [tumashu/chinese-fonts-setup#66]
在emacs 初始配置里面用了下面的配置会导致英文变成斜体。一旦用cfs-increase-fontsize改变字体大小，字体就回归原样。

(setq cfs-profiles '("program" "org-mode" "read-book"))

![screenshot from 2017-04-20 10-24-17](https://cloud.githubusercontent.com/assets/37181/25243897/879c9002-25b3-11e7-8796-2e1cac7d7fc1.png)

**Comment by tumashu** [comment]
下面是我的猜测:

我这边注释都是斜体, 我感觉这可能是 theme 设置的,  你用的这个字体可能只有几个字号有对应的斜体,所以字号一改变, 对应字号的斜体找不到了,只能用正常的

你可以用一个其他英文字体验证一下我的猜测

**Comment by tumashu** [comment]
这个issue我先关闭了, 有问题再开
