### ISSUE TITLE
在org-mode添加scheduled出现乱码

### ISSUE THREAD

**Issue by liulangdefeng2222** [tumashu/chinese-fonts-setup#67]
平台：window10+emacs25.1
您好，我是用chinese-fonts-setup插件生成的代码放到init.el文件中的。
![default](https://cloud.githubusercontent.com/assets/26605381/25633560/61becd46-2f2c-11e7-9a95-0cab9c82d63c.png)

在org文件里面打开包含中文的文件，中文显示是没有问题的，
![1493750340 1](https://cloud.githubusercontent.com/assets/26605381/25633451/f4ad6e24-2f2b-11e7-8051-e627f0238134.png)
但是C-c C-s插入时间的时候，就开始出现乱码
![default](https://cloud.githubusercontent.com/assets/26605381/25633503/26bcc43c-2f2c-11e7-8b35-4542696736ad.png)
回车插入的org文件中也是乱码
![1493750473 1](https://cloud.githubusercontent.com/assets/26605381/25633525/43c9eeba-2f2c-11e7-8b3c-b7b6562a75e4.png)
请问一下是什么问题呢？

**Comment by tumashu** [comment]
大多数是你的环境问题, 你拿下面的一段代码测试一下试试

```
(use-package mule
  :ensure nil
  :config

  (set-language-environment "UTF-8")
  (set-buffer-file-coding-system 'utf-8-unix)
  (set-clipboard-coding-system 'utf-8-unix)
  (set-file-name-coding-system 'utf-8-unix)
  (set-keyboard-coding-system 'utf-8-unix)
  (set-next-selection-coding-system 'utf-8-unix)
  (set-selection-coding-system 'utf-8-unix)
  (set-terminal-coding-system 'utf-8-unix)

  (when (eq system-type 'windows-nt)
    (set-language-environment "Chinese-GBK")
    (set-selection-coding-system 'gbk-dos)
    (set-next-selection-coding-system 'gbk-dos)
    (set-clipboard-coding-system 'gbk-dos)))

```

**Comment by liulangdefeng2222** [comment]
也是一样的问题，我用新建org文件也是这样

**Comment by tumashu** [comment]
在我这边，我的配置是没这个问题的， 更新一下 org 看看吧

**Comment by tumashu** [comment]
我猜测你自己的设置有问题， 因为我弹出的日历， 星期是中文，不是你上面的英文

**Comment by ayehome** [comment]
我的也是这个问题，貌似org 时间戳输出的是GBK编码，可以通过手动decode-coding-region正常显示，但是真麻烦啊

**Comment by tumashu** [comment]
我直接用英文时间戳，不存在这个问题
