### ISSUE TITLE
能否保存cfs--profiles-steps到profile里？

### ISSUE THREAD

**Issue by seagle0128** [tumashu/chinese-fonts-setup#68]
你好，在调用`cfs-edit-profile`后会保存 `cfs--profiles-steps`到init.el或者.emacs文件。能否将这些字体信息一并保存到对应的profile里呢？从设计和使用上讲这样更合理，profile文件就是为了保存独立的字体信息配置，除了字体名称外也应该包含字体大小等。另外一个原因和这个是一致的https://github.com/tumashu/chinese-fonts-setup/issues/57。

请参考，谢谢！

**Comment by tumashu** [comment]
能保存到 profile 目录中, 但不能保存到 profile 文件里面.

**Comment by tumashu** [comment]
如果从设计上来说, 可以将这些信息都分散的保存到每个 profile 文件中, 但是不建议这麽做
1.  profile 文件允许用户手工编辑, 如果用代码解析再保存, 用户的一些自定义的东西恢复起来很难,比如注释, 对齐方式等
2. 分散后,每次都要解析所有的 profile 文件, 有点罗嗦

**Comment by seagle0128** [comment]
统一保存到另外一个文件也是OK的，这样比以前合理多了。谢谢改进！
