### ISSUE TITLE
profile里第一行是9号字体，但emacs启动时却是12号字体，请教大神

### ISSUE THREAD

**Issue by nasoundead** [tumashu/chinese-fonts-setup#69]
![image](https://user-images.githubusercontent.com/13186459/27340776-f0e2b728-560d-11e7-9b2a-cc76161649c8.png)

**Comment by tumashu** [comment]
这是正常的

**Comment by tumashu** [comment]
用下面两个命今调整
cfs-increase-fontsize	增大字号
cfs-decrease-fontsize	减小字号

**Comment by nasoundead** [comment]
好的，我有点强迫症，所以我把(9  10.5    10.5)多复制了几行，这样启动时的字体就是我想要的了

**Comment by tumashu** [comment]
你这直接让 chinese-fonts-setup 残废了, 不过我只能说: 开心就好
