### ISSUE TITLE
建议支持直接在 配置文件中设置字体

### ISSUE THREAD

**Issue by lixuzhang** [tumashu/chinese-fonts-setup#7]
==========
原代码
==========
(defun cfs--read-profile ()
  "Get previously saved fonts names and scales from current profile"
  (interactive)
  (let ((file (cfs--get-current-profile)))
    (if (file-readable-p file)
        (progn (load-file file)
               (list
                (if (boundp 'cfs--custom-set-fonts-names)
                    cfs--custom-set-fonts-names
                  cfs--fontnames-fallback)
                (if (boundp 'cfs--custom-set-fonts-scales)
                    cfs--custom-set-fonts-scales
                  cfs--fontscales-fallback)))
      (list cfs--fontnames-fallback
            cfs--fontscales-fallback))))

==========
建议修改为
==========
(defun cfs--read-profile ()
  "Get previously saved fonts names and scales from current profile"
  (interactive)
  (let ((file (cfs--get-current-profile)))
    (if (file-readable-p file) (progn (load-file file)))
    (list
     (if (boundp 'cfs--custom-set-fonts-names)
         cfs--custom-set-fonts-names
       cfs--fontnames-fallback)
     (if (boundp 'cfs--custom-set-fonts-scales)
         cfs--custom-set-fonts-scales
       cfs--fontscales-fallback))))

==========
另外，建议将黑体放到后面，黑体太难看了。建议默认将等宽字体 比如：Courier New、新宋体、SimSun-ExtB 作为默认的首选字体，它们的fonts-scales为 '(1.09 1.08 1.14 1.12 1.11 1.2 1.13 1.15 1.14)

**Comment by tumashu** [comment]
这个issue我就关闭了。。。。
