### ISSUE TITLE
Another cfs.el already exists

### ISSUE THREAD

**Issue by tarsius** [tumashu/chinese-fonts-setup#70]
Another `cfs.el` already exists, see https://github.com/emacsattic/cfs. Please consider renaming your `cfs.el` to `cfs-core.el`.

The older `cfs.el` also used the prefix `cfs-`, which could lead to conflicts. I suggest you at least check if there already are conflicts.

**Comment by tumashu** [comment]
。。。

**Comment by tumashu** [comment]
chinese-fonts-setup do not use cfs- again, use cnfonts- instead

**Comment by tarsius** [comment]
That's the perfect solution. Thanks!
