### ISSUE TITLE
Compiling warning: chinese-fonts-setup.el:135:1:Warning: cl package required at runtime

### ISSUE THREAD

**Issue by xuchunyang** [tumashu/chinese-fonts-setup#8]
This line: https://github.com/tumashu/chinese-fonts-setup/blob/master/chinese-fonts-setup.el#L134

I don't know how to `require` the `cl` package correctly.

Beside the old Command Lisp package (`cl`) has been suggested to be replaced by `cl-lib` which has a more cleaner namespace by using `cl-` prefix.

**Comment by tumashu** [comment]
Fixed, Thanks!

**Comment by xuchunyang** [comment]
@tumashu Just a reminder, you can (maybe should) reference issues in your commit message and even [closing issue via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/), which will make your commit message more meaningful.

**Comment by tumashu** [comment]
Chunyang Xu <notifications@github.com> writes:

> @tumashu Just a reminder, you can (maybe should) reference issues in your commit message and even closing
> issue via commit messages, which will make your commit message more meaningful.

Thanks!

>
> —
> Reply to this email directly or view it on GitHub.

--
